import { readFileSync } from 'node:fs';
import { describe, expect, expectTypeOf, it } from 'vitest';
import type { components } from './schema.gen';
import { checkApi, type DegradedBody, type HealthBody } from './health';

const BASE_URL = 'http://api.test';

function jsonResponse(status: number, body: unknown): typeof fetch {
	return async () =>
		new Response(JSON.stringify(body), {
			status,
			headers: { 'content-type': 'application/json' }
		});
}

describe('checkApi', () => {
	it('CA-05.1: /healthz respondendo 200 → online', async () => {
		const status = await checkApi(jsonResponse(200, { status: 'ok', database: 'ok' }), BASE_URL);
		expect(status).toBe('online');
	});

	it('CA-05.2: /healthz respondendo 503 → degraded', async () => {
		const status = await checkApi(
			jsonResponse(503, { status: 'degraded', database: 'unavailable' }),
			BASE_URL
		);
		expect(status).toBe('degraded');
	});

	it('CA-05.3: backend parado (falha de rede) → unavailable, sem lançar erro', async () => {
		const refused: typeof fetch = async () => {
			throw new TypeError('fetch failed: ECONNREFUSED');
		};
		await expect(checkApi(refused, BASE_URL)).resolves.toBe('unavailable');
	});

	it('CA-05.3: backend que não responde dentro do prazo → unavailable', async () => {
		const hanging: typeof fetch = (_input, init) =>
			new Promise((_resolve, reject) => {
				init?.signal?.addEventListener('abort', () => reject(init.signal?.reason));
			});
		await expect(checkApi(hanging, BASE_URL, 50)).resolves.toBe('unavailable');
	});

	it('RN-13 / CA-05.1: chama o GET /healthz do contrato na URL base configurada', async () => {
		let called = '';
		const spy: typeof fetch = async (input) => {
			called = String(input);
			return new Response('{"status":"ok","database":"ok"}', { status: 200 });
		};
		await checkApi(spy, BASE_URL);
		expect(called).toBe('http://api.test/healthz');
	});
});

describe('tipos do contrato', () => {
	it('CA-04.4: o tipo da resposta de /healthz vem do arquivo gerado do openapi.yaml', () => {
		expectTypeOf<HealthBody>().toEqualTypeOf<components['schemas']['Health']>();
		expectTypeOf<DegradedBody>().toEqualTypeOf<components['schemas']['Health']>();

		const source = readFileSync(new URL('./health.ts', import.meta.url), 'utf8');
		expect(source).toMatch(/from '\.\/schema\.gen'/);
		const generated = readFileSync(new URL('./schema.gen.ts', import.meta.url), 'utf8');
		expect(generated).toMatch(/auto-generated by openapi-typescript/);
	});
});
