/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado da API e do banco
         * @description Responde 200 quando o banco responde a um ping em até 2 segundos (RN-06) e 503 quando não responde nesse prazo (RN-07).
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca o código do Discord por uma sessão
         * @description Chamado pelo servidor do web depois do retorno do Discord (ADR-07). A API troca o código no Discord, cria ou atualiza o Usuário pelo ID do Discord e abre uma Sessão (RN-04, RN-05, RN-07). Se o Discord falhar, nada é criado (RN-13).
         */
        post: operations["createSessionFromDiscord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuário da sessão
         * @description Responde 401 sem sessão válida (RN-10, RN-16).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Encerra a sessão atual
         * @description Apaga só esta Sessão; outras sessões do Usuário continuam (RN-11).
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "unavailable";
        };
        DiscordLogin: {
            code: string;
            /**
             * Format: uri
             * @description O mesmo redirect_uri usado na autorização (D-08).
             */
            redirectUri: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @description Nome de exibição no Discord; nulo quando a pessoa não definiu. */
            globalName: string | null;
        };
        SessionCreated: {
            /** @description Vai só para o cookie HttpOnly do web; o banco guarda o hash (RN-07). */
            sessionToken: string;
            user: components["schemas"]["User"];
        };
        Error: {
            /** @enum {string} */
            error: "invalid_code" | "discord_unavailable" | "no_session";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API e banco saudáveis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "database": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description API no ar, mas o banco não respondeu em até 2 segundos. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded",
                     *       "database": "unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createSessionFromDiscord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordLogin"];
            };
        };
        responses: {
            /** @description Sessão criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description O Discord recusou o código, ou o pedido veio sem código. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid_code"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description O Discord não respondeu em até 5 segundos ou respondeu com erro. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "discord_unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário da sessão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Sem sessão, ou sessão desconhecida ou vencida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "no_session"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada (ou já não existia). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
