/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado da API e do banco
         * @description Responde 200 quando o banco responde a um ping em até 2 segundos (RN-06) e 503 quando não responde nesse prazo (RN-07).
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/discord": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca o código do Discord por uma sessão
         * @description Chamado pelo servidor do web depois do retorno do Discord (ADR-07). A API troca o código no Discord, cria ou atualiza o Usuário pelo ID do Discord e abre uma Sessão (RN-04, RN-05, RN-07). Se o Discord falhar, nada é criado (RN-13).
         */
        post: operations["createSessionFromDiscord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuário da sessão
         * @description Responde 401 sem sessão válida (RN-10, RN-16).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Encerra a sessão atual
         * @description Apaga só esta Sessão; outras sessões do Usuário continuam (RN-11).
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de classes
         * @description As classes do bRO, conforme o bROWiki, na ordem da página (spec personagens, RN-06, RN-20). Não exige sessão.
         */
        get: operations["listClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personagens do Usuário da sessão
         * @description O principal primeiro, depois por ordem de cadastro (RN-01, RN-17).
         */
        get: operations["listCharacters"];
        put?: never;
        /**
         * Cadastra um personagem
         * @description O primeiro personagem do Usuário vira o principal (RN-12). O nick é único em todo o RO Lobby, sem diferenciar maiúsculas (RN-05), e cada Usuário tem até 10 personagens (RN-11).
         */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Edita um personagem
         * @description Grava todos os campos, com as mesmas regras do cadastro (RN-15).
         */
        put: operations["updateCharacter"];
        post?: never;
        /**
         * Exclui um personagem
         * @description Se era o principal, o mais antigo que sobrar vira o principal (RN-14).
         */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/main": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Torna o personagem o principal
         * @description O principal anterior deixa de ser (RN-13, D-01).
         */
        put: operations["setMainCharacter"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo de instâncias
         * @description As instâncias de grupo do bROWiki, na ordem da escolha: nível 130 ou mais primeiro, depois as de nível menor; em cada parte, nível decrescente (spec lobbies, RN-01, RN-02). Não exige sessão.
         */
        get: operations["listInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lobbies abertos num intervalo de dias
         * @description Lobbies abertos (não cancelados e ainda não iniciados) com início entre os dias from e to, no fuso de São Paulo, por horário (RN-13, RN-14, RN-22). Não exige sessão.
         */
        get: operations["listLobbies"];
        put?: never;
        /**
         * Cria um lobby
         * @description O dono escolhe um dos próprios personagens, que ocupa a vaga da função dele (RN-08). Cada Usuário tem até 5 lobbies abertos (RN-11), e o personagem não pode estar em outro lobby a menos de 2 h (RN-10).
         */
        post: operations["createLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lobbies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        /**
         * Detalhe do lobby
         * @description O lobby em qualquer estado (RN-15). Não exige sessão.
         */
        get: operations["getLobby"];
        /**
         * Edita o lobby
         * @description Só o dono e só com o lobby aberto. Muda início, vagas, nível mínimo e observação; instância e personagem ficam (RN-17, RN-18).
         */
        put: operations["updateLobby"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lobbies/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela o lobby
         * @description Só o dono e só com o lobby aberto, com motivo de 10 a 250 caracteres (RN-19).
         */
        post: operations["cancelLobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "unavailable";
        };
        DiscordLogin: {
            code: string;
            /**
             * Format: uri
             * @description O mesmo redirect_uri usado na autorização (D-08).
             */
            redirectUri: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @description Nome de exibição no Discord; nulo quando a pessoa não definiu. */
            globalName: string | null;
        };
        SessionCreated: {
            /** @description Vai só para o cookie HttpOnly do web; o banco guarda o hash (RN-07). */
            sessionToken: string;
            user: components["schemas"]["User"];
        };
        Error: {
            /** @enum {string} */
            error: "invalid_code" | "discord_unavailable" | "no_session" | "not_found" | "character_limit" | "character_in_open_lobby" | "lobby_limit" | "lobby_not_open" | "invalid_range";
        };
        /**
         * @description Função do personagem (RN-08).
         * @enum {string}
         */
        Role: "tank" | "support" | "dps";
        /**
         * @description Retrato da lista do RO Lobby (RN-10, D-04). Cada valor tem um arquivo em web/static/portraits/.
         * @enum {string}
         */
        Portrait: "retrato-1" | "retrato-2" | "retrato-3" | "retrato-4";
        /** @enum {string} */
        ClassTier: "aprendiz" | "primeira" | "segunda" | "transcendental" | "terceira" | "quarta" | "expandida";
        Class: {
            /**
             * @description Nome sem acento em kebab-case; é o que o personagem guarda (D-03).
             * @example guardiao-real
             */
            id: string;
            /** @example Guardião Real */
            name: string;
            /**
             * @description Título da página da classe no bROWiki.
             * @example Guardiões Reais
             */
            plural: string;
            tier: components["schemas"]["ClassTier"];
            /**
             * @description Classe de 1ª (ou a base, nas expandidas) de onde a linha sai.
             * @example Espadachim
             */
            family: string;
        };
        /** @description Dados de um personagem. A API valida todos os campos (RNF-04), com as regras RN-04 a RN-10; um valor fora delas volta 422. */
        CharacterInput: {
            /** @description 1 a 24 caracteres depois de tirar os espaços das pontas. */
            nick: string;
            /** @description ID de uma classe de GET /classes. */
            classId: string;
            /** @description De 1 a 275. */
            level: number;
            role: components["schemas"]["Role"];
            portrait?: components["schemas"]["Portrait"];
            /** @description Opcional; https:// e até 300 caracteres. Vazio fica sem link. */
            link?: string;
        };
        Character: {
            /** Format: uuid */
            id: string;
            nick: string;
            classId: string;
            level: number;
            role: components["schemas"]["Role"];
            portrait: components["schemas"]["Portrait"];
            link: string | null;
            isMain: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        FieldError: {
            /** @enum {string} */
            field: "nick" | "classId" | "level" | "role" | "portrait" | "link" | "instanceId" | "startsAt" | "slots" | "minLevel" | "characterId" | "note" | "reason";
            /** @enum {string} */
            code: "required" | "too_long" | "too_short" | "invalid" | "taken" | "conflict" | "below_occupied" | "above_owner" | "level_too_low";
        };
        ValidationError: {
            /** @enum {string} */
            error: "validation";
            fields: components["schemas"]["FieldError"][];
        };
        /**
         * @description Tempo de retorno da instância, como o bROWiki agrupa.
         * @enum {string}
         */
        InstanceReset: "daily" | "three_days" | "hours" | "weekly";
        Instance: {
            /** @example templo-do-demonio-rei */
            id: string;
            /** @example Templo do Demônio Rei */
            name: string;
            /**
             * @description Nível de entrada.
             * @example 160
             */
            level: number;
            reset: components["schemas"]["InstanceReset"];
        };
        Slots: {
            tank: number;
            support: number;
            dps: number;
        };
        LobbyInput: {
            /** @description ID de uma instância de GET /instances. */
            instanceId: string;
            /**
             * Format: date-time
             * @description Início em UTC; o web converte o dia e a hora de Brasília (D-04).
             */
            startsAt: string;
            slots: components["schemas"]["Slots"];
            minLevel: number;
            /** @description Um dos personagens do Usuário da sessão. */
            characterId: string;
            /** @description Opcional, até 250 caracteres. */
            note?: string;
        };
        LobbyUpdate: {
            /** Format: date-time */
            startsAt: string;
            slots: components["schemas"]["Slots"];
            minLevel: number;
            note?: string;
        };
        CancelLobby: {
            /** @description De 10 a 250 caracteres. */
            reason: string;
        };
        /** @enum {string} */
        LobbyStatus: "open" | "started" | "cancelled";
        LobbyInstance: {
            id: string;
            /** @description Nome guardado na criação (D-02). */
            name: string;
            level: number;
            /**
             * @description Nulo se a instância saiu do catálogo.
             * @enum {string|null}
             */
            reset: "daily" | "three_days" | "hours" | "weekly" | null;
        };
        LobbyOwner: {
            /** Format: uuid */
            userId: string;
            discordName: string;
            /**
             * Format: uuid
             * @description Nulo se o personagem foi excluído depois do início (D-01).
             */
            characterId: string | null;
            nick: string | null;
            classId: string | null;
            level: number | null;
            /**
             * @description Retrato do personagem do dono (RN-15); nulo se ele foi excluído.
             * @enum {string|null}
             */
            portrait: "retrato-1" | "retrato-2" | "retrato-3" | "retrato-4" | null;
            role: components["schemas"]["Role"];
        };
        Lobby: {
            /** Format: uuid */
            id: string;
            instance: components["schemas"]["LobbyInstance"];
            /** Format: date-time */
            startsAt: string;
            status: components["schemas"]["LobbyStatus"];
            slots: components["schemas"]["Slots"];
            occupied: components["schemas"]["Slots"];
            minLevel: number;
            note: string | null;
            owner: components["schemas"]["LobbyOwner"];
            cancelReason: string | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description O lobby não existe ou, nas escritas, é de outro Usuário (RN-20). */
        LobbyNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not_found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description O lobby já começou ou foi cancelado (D-08). */
        LobbyNotOpen: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "lobby_not_open"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sem sessão, ou sessão desconhecida ou vencida. */
        NoSession: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "no_session"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description O personagem não existe ou é de outro Usuário (RN-02). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not_found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Campos inválidos, com o código de cada erro (RN-19, D-07). */
        Invalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "validation",
                 *       "fields": [
                 *         {
                 *           "field": "nick",
                 *           "code": "taken"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
        LobbyId: string;
        /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
        CharacterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API e banco saudáveis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "database": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description API no ar, mas o banco não respondeu em até 2 segundos. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "degraded",
                     *       "database": "unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    createSessionFromDiscord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscordLogin"];
            };
        };
        responses: {
            /** @description Sessão criada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description O Discord recusou o código, ou o pedido veio sem código. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid_code"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description O Discord não respondeu em até 5 segundos ou respondeu com erro. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "discord_unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário da sessão. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Sem sessão, ou sessão desconhecida ou vencida. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "no_session"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão encerrada (ou já não existia). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listClasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as classes do catálogo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"][];
                };
            };
        };
    };
    listCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personagens do Usuário. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
            401: components["responses"]["NoSession"];
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterInput"];
            };
        };
        responses: {
            /** @description Personagem criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            401: components["responses"]["NoSession"];
            /** @description O Usuário já tem 10 personagens (RN-11). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "character_limit"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterInput"];
            };
        };
        responses: {
            /** @description Personagem editado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            401: components["responses"]["NoSession"];
            404: components["responses"]["NotFound"];
            /** @description O personagem é dono de um lobby aberto (RN-21 da spec lobbies). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "character_in_open_lobby"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personagem excluído. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NoSession"];
            404: components["responses"]["NotFound"];
            /** @description O personagem é dono de um lobby aberto (RN-21 da spec lobbies). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "character_in_open_lobby"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setMainCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do personagem. Um ID desconhecido, malformado ou de outro Usuário responde 404 do mesmo jeito (RN-02, D-08). */
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personagem marcado como principal. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NoSession"];
            404: components["responses"]["NotFound"];
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as instâncias do catálogo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"][];
                };
            };
        };
    };
    listLobbies: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lobbies abertos do intervalo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"][];
                };
            };
            /** @description Intervalo de datas inválido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid_range"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createLobby: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LobbyInput"];
            };
        };
        responses: {
            /** @description Lobby criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            401: components["responses"]["NoSession"];
            /** @description O Usuário já tem 5 lobbies abertos (RN-11). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "lobby_limit"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Invalid"];
        };
    };
    getLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O lobby. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            404: components["responses"]["LobbyNotFound"];
        };
    };
    updateLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LobbyUpdate"];
            };
        };
        responses: {
            /** @description Lobby editado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            401: components["responses"]["NoSession"];
            404: components["responses"]["LobbyNotFound"];
            409: components["responses"]["LobbyNotOpen"];
            422: components["responses"]["Invalid"];
        };
    };
    cancelLobby: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID do lobby. Desconhecido, malformado ou, nas escritas, de outro Usuário responde 404 do mesmo jeito (RN-20, D-08). */
                id: components["parameters"]["LobbyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelLobby"];
            };
        };
        responses: {
            /** @description Lobby cancelado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lobby"];
                };
            };
            401: components["responses"]["NoSession"];
            404: components["responses"]["LobbyNotFound"];
            409: components["responses"]["LobbyNotOpen"];
            422: components["responses"]["Invalid"];
        };
    };
}
