//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ClassTier.
const (
	ClassTierAprendiz       ClassTier = "aprendiz"
	ClassTierExpandida      ClassTier = "expandida"
	ClassTierPrimeira       ClassTier = "primeira"
	ClassTierQuarta         ClassTier = "quarta"
	ClassTierSegunda        ClassTier = "segunda"
	ClassTierTerceira       ClassTier = "terceira"
	ClassTierTranscendental ClassTier = "transcendental"
)

// Valid indicates whether the value is a known member of the ClassTier enum.
func (e ClassTier) Valid() bool {
	switch e {
	case ClassTierAprendiz:
		return true
	case ClassTierExpandida:
		return true
	case ClassTierPrimeira:
		return true
	case ClassTierQuarta:
		return true
	case ClassTierSegunda:
		return true
	case ClassTierTerceira:
		return true
	case ClassTierTranscendental:
		return true
	default:
		return false
	}
}

// Defines values for ErrorError.
const (
	ErrorErrorCharacterInOpenLobby ErrorError = "character_in_open_lobby"
	ErrorErrorCharacterLimit       ErrorError = "character_limit"
	ErrorErrorDiscordUnavailable   ErrorError = "discord_unavailable"
	ErrorErrorInvalidCode          ErrorError = "invalid_code"
	ErrorErrorInvalidRange         ErrorError = "invalid_range"
	ErrorErrorLobbyLimit           ErrorError = "lobby_limit"
	ErrorErrorLobbyNotOpen         ErrorError = "lobby_not_open"
	ErrorErrorNoSession            ErrorError = "no_session"
	ErrorErrorNotFound             ErrorError = "not_found"
)

// Valid indicates whether the value is a known member of the ErrorError enum.
func (e ErrorError) Valid() bool {
	switch e {
	case ErrorErrorCharacterInOpenLobby:
		return true
	case ErrorErrorCharacterLimit:
		return true
	case ErrorErrorDiscordUnavailable:
		return true
	case ErrorErrorInvalidCode:
		return true
	case ErrorErrorInvalidRange:
		return true
	case ErrorErrorLobbyLimit:
		return true
	case ErrorErrorLobbyNotOpen:
		return true
	case ErrorErrorNoSession:
		return true
	case ErrorErrorNotFound:
		return true
	default:
		return false
	}
}

// Defines values for FieldErrorCode.
const (
	FieldErrorCodeAboveOwner    FieldErrorCode = "above_owner"
	FieldErrorCodeBelowOccupied FieldErrorCode = "below_occupied"
	FieldErrorCodeConflict      FieldErrorCode = "conflict"
	FieldErrorCodeInvalid       FieldErrorCode = "invalid"
	FieldErrorCodeLevelTooLow   FieldErrorCode = "level_too_low"
	FieldErrorCodeRequired      FieldErrorCode = "required"
	FieldErrorCodeTaken         FieldErrorCode = "taken"
	FieldErrorCodeTooLong       FieldErrorCode = "too_long"
	FieldErrorCodeTooShort      FieldErrorCode = "too_short"
)

// Valid indicates whether the value is a known member of the FieldErrorCode enum.
func (e FieldErrorCode) Valid() bool {
	switch e {
	case FieldErrorCodeAboveOwner:
		return true
	case FieldErrorCodeBelowOccupied:
		return true
	case FieldErrorCodeConflict:
		return true
	case FieldErrorCodeInvalid:
		return true
	case FieldErrorCodeLevelTooLow:
		return true
	case FieldErrorCodeRequired:
		return true
	case FieldErrorCodeTaken:
		return true
	case FieldErrorCodeTooLong:
		return true
	case FieldErrorCodeTooShort:
		return true
	default:
		return false
	}
}

// Defines values for FieldErrorField.
const (
	FieldErrorFieldCharacterId FieldErrorField = "characterId"
	FieldErrorFieldClassId     FieldErrorField = "classId"
	FieldErrorFieldInstanceId  FieldErrorField = "instanceId"
	FieldErrorFieldLevel       FieldErrorField = "level"
	FieldErrorFieldLink        FieldErrorField = "link"
	FieldErrorFieldMinLevel    FieldErrorField = "minLevel"
	FieldErrorFieldNick        FieldErrorField = "nick"
	FieldErrorFieldNote        FieldErrorField = "note"
	FieldErrorFieldPortrait    FieldErrorField = "portrait"
	FieldErrorFieldReason      FieldErrorField = "reason"
	FieldErrorFieldRole        FieldErrorField = "role"
	FieldErrorFieldSlots       FieldErrorField = "slots"
	FieldErrorFieldStartsAt    FieldErrorField = "startsAt"
)

// Valid indicates whether the value is a known member of the FieldErrorField enum.
func (e FieldErrorField) Valid() bool {
	switch e {
	case FieldErrorFieldCharacterId:
		return true
	case FieldErrorFieldClassId:
		return true
	case FieldErrorFieldInstanceId:
		return true
	case FieldErrorFieldLevel:
		return true
	case FieldErrorFieldLink:
		return true
	case FieldErrorFieldMinLevel:
		return true
	case FieldErrorFieldNick:
		return true
	case FieldErrorFieldNote:
		return true
	case FieldErrorFieldPortrait:
		return true
	case FieldErrorFieldReason:
		return true
	case FieldErrorFieldRole:
		return true
	case FieldErrorFieldSlots:
		return true
	case FieldErrorFieldStartsAt:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	HealthDatabaseOk          HealthDatabase = "ok"
	HealthDatabaseUnavailable HealthDatabase = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseOk:
		return true
	case HealthDatabaseUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for InstanceReset.
const (
	InstanceResetDaily     InstanceReset = "daily"
	InstanceResetHours     InstanceReset = "hours"
	InstanceResetThreeDays InstanceReset = "three_days"
	InstanceResetWeekly    InstanceReset = "weekly"
)

// Valid indicates whether the value is a known member of the InstanceReset enum.
func (e InstanceReset) Valid() bool {
	switch e {
	case InstanceResetDaily:
		return true
	case InstanceResetHours:
		return true
	case InstanceResetThreeDays:
		return true
	case InstanceResetWeekly:
		return true
	default:
		return false
	}
}

// Defines values for LobbyInstanceReset.
const (
	LobbyInstanceResetDaily     LobbyInstanceReset = "daily"
	LobbyInstanceResetHours     LobbyInstanceReset = "hours"
	LobbyInstanceResetThreeDays LobbyInstanceReset = "three_days"
	LobbyInstanceResetWeekly    LobbyInstanceReset = "weekly"
)

// Valid indicates whether the value is a known member of the LobbyInstanceReset enum.
func (e LobbyInstanceReset) Valid() bool {
	switch e {
	case LobbyInstanceResetDaily:
		return true
	case LobbyInstanceResetHours:
		return true
	case LobbyInstanceResetThreeDays:
		return true
	case LobbyInstanceResetWeekly:
		return true
	default:
		return false
	}
}

// Defines values for LobbyStatus.
const (
	LobbyStatusCancelled LobbyStatus = "cancelled"
	LobbyStatusOpen      LobbyStatus = "open"
	LobbyStatusStarted   LobbyStatus = "started"
)

// Valid indicates whether the value is a known member of the LobbyStatus enum.
func (e LobbyStatus) Valid() bool {
	switch e {
	case LobbyStatusCancelled:
		return true
	case LobbyStatusOpen:
		return true
	case LobbyStatusStarted:
		return true
	default:
		return false
	}
}

// Defines values for Portrait.
const (
	PortraitRetrato1 Portrait = "retrato-1"
	PortraitRetrato2 Portrait = "retrato-2"
	PortraitRetrato3 Portrait = "retrato-3"
	PortraitRetrato4 Portrait = "retrato-4"
)

// Valid indicates whether the value is a known member of the Portrait enum.
func (e Portrait) Valid() bool {
	switch e {
	case PortraitRetrato1:
		return true
	case PortraitRetrato2:
		return true
	case PortraitRetrato3:
		return true
	case PortraitRetrato4:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleDps     Role = "dps"
	RoleSupport Role = "support"
	RoleTank    Role = "tank"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleDps:
		return true
	case RoleSupport:
		return true
	case RoleTank:
		return true
	default:
		return false
	}
}

// Defines values for ValidationErrorError.
const (
	ValidationErrorErrorValidation ValidationErrorError = "validation"
)

// Valid indicates whether the value is a known member of the ValidationErrorError enum.
func (e ValidationErrorError) Valid() bool {
	switch e {
	case ValidationErrorErrorValidation:
		return true
	default:
		return false
	}
}

// CancelLobby defines model for CancelLobby.
type CancelLobby struct {
	// Reason De 10 a 250 caracteres.
	Reason string `json:"reason"`
}

// Character defines model for Character.
type Character struct {
	ClassId   string             `json:"classId"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	IsMain    bool               `json:"isMain"`
	Level     int                `json:"level"`
	Link      *string            `json:"link"`
	Nick      string             `json:"nick"`

	// Portrait Retrato da lista do RO Lobby (RN-10, D-04). Cada valor tem um arquivo em web/static/portraits/.
	Portrait Portrait `json:"portrait"`

	// Role Função do personagem (RN-08).
	Role Role `json:"role"`
}

// CharacterInput Dados de um personagem. A API valida todos os campos (RNF-04), com as regras RN-04 a RN-10; um valor fora delas volta 422.
type CharacterInput struct {
	// ClassId ID de uma classe de GET /classes.
	ClassId string `json:"classId"`

	// Level De 1 a 275.
	Level int `json:"level"`

	// Link Opcional; https:// e até 300 caracteres. Vazio fica sem link.
	Link *string `json:"link,omitempty"`

	// Nick 1 a 24 caracteres depois de tirar os espaços das pontas.
	Nick string `json:"nick"`

	// Portrait Retrato da lista do RO Lobby (RN-10, D-04). Cada valor tem um arquivo em web/static/portraits/.
	Portrait *Portrait `json:"portrait,omitempty"`

	// Role Função do personagem (RN-08).
	Role Role `json:"role"`
}

// Class defines model for Class.
type Class struct {
	// Family Classe de 1ª (ou a base, nas expandidas) de onde a linha sai.
	//
	// Example: Espadachim
	Family string `json:"family"`

	// Id Nome sem acento em kebab-case; é o que o personagem guarda (D-03).
	//
	// Example: guardiao-real
	Id string `json:"id"`

	// Name Example: Guardião Real
	Name string `json:"name"`

	// Plural Título da página da classe no bROWiki.
	//
	// Example: Guardiões Reais
	Plural string    `json:"plural"`
	Tier   ClassTier `json:"tier"`
}

// ClassTier defines model for ClassTier.
type ClassTier string

// DiscordLogin defines model for DiscordLogin.
type DiscordLogin struct {
	Code string `json:"code"`

	// RedirectUri O mesmo redirect_uri usado na autorização (D-08).
	RedirectUri string `json:"redirectUri"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorError `json:"error"`
}

// ErrorError defines model for Error.Error.
type ErrorError string

// FieldError defines model for FieldError.
type FieldError struct {
	Code  FieldErrorCode  `json:"code"`
	Field FieldErrorField `json:"field"`
}

// FieldErrorCode defines model for FieldError.Code.
type FieldErrorCode string

// FieldErrorField defines model for FieldError.Field.
type FieldErrorField string

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Instance defines model for Instance.
type Instance struct {
	// Id Example: templo-do-demonio-rei
	Id string `json:"id"`

	// Level Nível de entrada.
	//
	// Example: 160
	Level int `json:"level"`

	// Name Example: Templo do Demônio Rei
	Name string `json:"name"`

	// Reset Tempo de retorno da instância, como o bROWiki agrupa.
	Reset InstanceReset `json:"reset"`
}

// InstanceReset Tempo de retorno da instância, como o bROWiki agrupa.
type InstanceReset string

// Lobby defines model for Lobby.
type Lobby struct {
	CancelReason *string            `json:"cancelReason"`
	CreatedAt    time.Time          `json:"createdAt"`
	Id           openapi_types.UUID `json:"id"`
	Instance     LobbyInstance      `json:"instance"`
	MinLevel     int                `json:"minLevel"`
	Note         *string            `json:"note"`
	Occupied     Slots              `json:"occupied"`
	Owner        LobbyOwner         `json:"owner"`
	Slots        Slots              `json:"slots"`
	StartsAt     time.Time          `json:"startsAt"`
	Status       LobbyStatus        `json:"status"`
}

// LobbyInput defines model for LobbyInput.
type LobbyInput struct {
	// CharacterId Um dos personagens do Usuário da sessão.
	CharacterId string `json:"characterId"`

	// InstanceId ID de uma instância de GET /instances.
	InstanceId string `json:"instanceId"`
	MinLevel   int    `json:"minLevel"`

	// Note Opcional, até 250 caracteres.
	Note  *string `json:"note,omitempty"`
	Slots Slots   `json:"slots"`

	// StartsAt Início em UTC; o web converte o dia e a hora de Brasília (D-04).
	StartsAt time.Time `json:"startsAt"`
}

// LobbyInstance defines model for LobbyInstance.
type LobbyInstance struct {
	Id    string `json:"id"`
	Level int    `json:"level"`

	// Name Nome guardado na criação (D-02).
	Name string `json:"name"`

	// Reset Nulo se a instância saiu do catálogo.
	Reset *LobbyInstanceReset `json:"reset"`
}

// LobbyInstanceReset Nulo se a instância saiu do catálogo.
type LobbyInstanceReset string

// LobbyOwner defines model for LobbyOwner.
type LobbyOwner struct {
	// CharacterId Nulo se o personagem foi excluído depois do início (D-01).
	CharacterId *openapi_types.UUID `json:"characterId"`
	ClassId     *string             `json:"classId"`
	DiscordName string              `json:"discordName"`
	Level       *int                `json:"level"`
	Nick        *string             `json:"nick"`

	// Role Função do personagem (RN-08).
	Role   Role               `json:"role"`
	UserId openapi_types.UUID `json:"userId"`
}

// LobbyStatus defines model for LobbyStatus.
type LobbyStatus string

// LobbyUpdate defines model for LobbyUpdate.
type LobbyUpdate struct {
	MinLevel int       `json:"minLevel"`
	Note     *string   `json:"note,omitempty"`
	Slots    Slots     `json:"slots"`
	StartsAt time.Time `json:"startsAt"`
}

// Portrait Retrato da lista do RO Lobby (RN-10, D-04). Cada valor tem um arquivo em web/static/portraits/.
type Portrait string

// Role Função do personagem (RN-08).
type Role string

// SessionCreated defines model for SessionCreated.
type SessionCreated struct {
	// SessionToken Vai só para o cookie HttpOnly do web; o banco guarda o hash (RN-07).
	SessionToken string `json:"sessionToken"`
	User         User   `json:"user"`
}

// Slots defines model for Slots.
type Slots struct {
	Dps     int `json:"dps"`
	Support int `json:"support"`
	Tank    int `json:"tank"`
}

// User defines model for User.
type User struct {
	// GlobalName Nome de exibição no Discord; nulo quando a pessoa não definiu.
	GlobalName *string            `json:"globalName"`
	Id         openapi_types.UUID `json:"id"`
	Username   string             `json:"username"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error  ValidationErrorError `json:"error"`
	Fields []FieldError         `json:"fields"`
}

// ValidationErrorError defines model for ValidationError.Error.
type ValidationErrorError string

// CharacterId defines model for CharacterId.
type CharacterId = string

// LobbyId defines model for LobbyId.
type LobbyId = string

// Invalid defines model for Invalid.
type Invalid = ValidationError

// LobbyNotFound defines model for LobbyNotFound.
type LobbyNotFound = Error

// LobbyNotOpen defines model for LobbyNotOpen.
type LobbyNotOpen = Error

// NoSession defines model for NoSession.
type NoSession = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListLobbiesParams defines parameters for ListLobbies.
type ListLobbiesParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// CreateSessionFromDiscordJSONRequestBody defines body for CreateSessionFromDiscord for application/json ContentType.
type CreateSessionFromDiscordJSONRequestBody = DiscordLogin

// CreateCharacterJSONRequestBody defines body for CreateCharacter for application/json ContentType.
type CreateCharacterJSONRequestBody = CharacterInput

// UpdateCharacterJSONRequestBody defines body for UpdateCharacter for application/json ContentType.
type UpdateCharacterJSONRequestBody = CharacterInput

// CreateLobbyJSONRequestBody defines body for CreateLobby for application/json ContentType.
type CreateLobbyJSONRequestBody = LobbyInput

// UpdateLobbyJSONRequestBody defines body for UpdateLobby for application/json ContentType.
type UpdateLobbyJSONRequestBody = LobbyUpdate

// CancelLobbyJSONRequestBody defines body for CancelLobby for application/json ContentType.
type CancelLobbyJSONRequestBody = CancelLobby

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateSessionFromDiscord Troca o código do Discord por uma sessão
	// (POST /auth/discord)
	CreateSessionFromDiscord(w http.ResponseWriter, r *http.Request)
	// ListCharacters Personagens do Usuário da sessão
	// (GET /characters)
	ListCharacters(w http.ResponseWriter, r *http.Request)
	// CreateCharacter Cadastra um personagem
	// (POST /characters)
	CreateCharacter(w http.ResponseWriter, r *http.Request)
	// DeleteCharacter Exclui um personagem
	// (DELETE /characters/{id})
	DeleteCharacter(w http.ResponseWriter, r *http.Request, id CharacterId)
	// UpdateCharacter Edita um personagem
	// (PUT /characters/{id})
	UpdateCharacter(w http.ResponseWriter, r *http.Request, id CharacterId)
	// SetMainCharacter Torna o personagem o principal
	// (PUT /characters/{id}/main)
	SetMainCharacter(w http.ResponseWriter, r *http.Request, id CharacterId)
	// ListClasses Catálogo de classes
	// (GET /classes)
	ListClasses(w http.ResponseWriter, r *http.Request)
	// GetHealthz Estado da API e do banco
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListInstances Catálogo de instâncias
	// (GET /instances)
	ListInstances(w http.ResponseWriter, r *http.Request)
	// ListLobbies Lobbies abertos num intervalo de dias
	// (GET /lobbies)
	ListLobbies(w http.ResponseWriter, r *http.Request, params ListLobbiesParams)
	// CreateLobby Cria um lobby
	// (POST /lobbies)
	CreateLobby(w http.ResponseWriter, r *http.Request)
	// GetLobby Detalhe do lobby
	// (GET /lobbies/{id})
	GetLobby(w http.ResponseWriter, r *http.Request, id LobbyId)
	// UpdateLobby Edita o lobby
	// (PUT /lobbies/{id})
	UpdateLobby(w http.ResponseWriter, r *http.Request, id LobbyId)
	// CancelLobby Cancela o lobby
	// (POST /lobbies/{id}/cancel)
	CancelLobby(w http.ResponseWriter, r *http.Request, id LobbyId)
	// GetMe Usuário da sessão
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// DeleteSession Encerra a sessão atual
	// (DELETE /session)
	DeleteSession(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateSessionFromDiscord operation middleware
func (siw *ServerInterfaceWrapper) CreateSessionFromDiscord(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSessionFromDiscord(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCharacters operation middleware
func (siw *ServerInterfaceWrapper) ListCharacters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCharacters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCharacter operation middleware
func (siw *ServerInterfaceWrapper) CreateCharacter(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCharacter operation middleware
func (siw *ServerInterfaceWrapper) DeleteCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CharacterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCharacter(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCharacter operation middleware
func (siw *ServerInterfaceWrapper) UpdateCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CharacterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCharacter(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetMainCharacter operation middleware
func (siw *ServerInterfaceWrapper) SetMainCharacter(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id CharacterId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetMainCharacter(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClasses operation middleware
func (siw *ServerInterfaceWrapper) ListClasses(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClasses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLobbies operation middleware
func (siw *ServerInterfaceWrapper) ListLobbies(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLobbiesParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLobbies(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLobby operation middleware
func (siw *ServerInterfaceWrapper) CreateLobby(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLobby(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLobby operation middleware
func (siw *ServerInterfaceWrapper) GetLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id LobbyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLobby(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLobby operation middleware
func (siw *ServerInterfaceWrapper) UpdateLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id LobbyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLobby(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelLobby operation middleware
func (siw *ServerInterfaceWrapper) CancelLobby(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id LobbyId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelLobby(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/discord", wrapper.CreateSessionFromDiscord)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/session", wrapper.DeleteSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/classes", wrapper.ListClasses)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/characters", wrapper.ListCharacters)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/characters", wrapper.CreateCharacter)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/characters/{id}", wrapper.DeleteCharacter)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/characters/{id}", wrapper.UpdateCharacter)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/characters/{id}/main", wrapper.SetMainCharacter)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/instances", wrapper.ListInstances)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/lobbies", wrapper.ListLobbies)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lobbies", wrapper.CreateLobby)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/lobbies/{id}", wrapper.GetLobby)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/lobbies/{id}", wrapper.UpdateLobby)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lobbies/{id}/cancel", wrapper.CancelLobby)

	return m
}

type InvalidJSONResponse ValidationError

type LobbyNotFoundJSONResponse Error

type LobbyNotOpenJSONResponse Error

type NoSessionJSONResponse Error

type NotFoundJSONResponse Error

type CreateSessionFromDiscordRequestObject struct {
	Body *CreateSessionFromDiscordJSONRequestBody
}

type CreateSessionFromDiscordResponseObject interface {
	VisitCreateSessionFromDiscordResponse(w http.ResponseWriter) error
}

type CreateSessionFromDiscord201JSONResponse SessionCreated

func (response CreateSessionFromDiscord201JSONResponse) VisitCreateSessionFromDiscordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionFromDiscord400JSONResponse Error

func (response CreateSessionFromDiscord400JSONResponse) VisitCreateSessionFromDiscordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionFromDiscord502JSONResponse Error

func (response CreateSessionFromDiscord502JSONResponse) VisitCreateSessionFromDiscordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type ListCharactersRequestObject struct {
}

type ListCharactersResponseObject interface {
	VisitListCharactersResponse(w http.ResponseWriter) error
}

type ListCharacters200JSONResponse []Character

func (response ListCharacters200JSONResponse) VisitListCharactersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCharacters401JSONResponse struct{ NoSessionJSONResponse }

func (response ListCharacters401JSONResponse) VisitListCharactersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacterRequestObject struct {
	Body *CreateCharacterJSONRequestBody
}

type CreateCharacterResponseObject interface {
	VisitCreateCharacterResponse(w http.ResponseWriter) error
}

type CreateCharacter201JSONResponse Character

func (response CreateCharacter201JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter401JSONResponse struct{ NoSessionJSONResponse }

func (response CreateCharacter401JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter409JSONResponse Error

func (response CreateCharacter409JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCharacter422JSONResponse struct{ InvalidJSONResponse }

func (response CreateCharacter422JSONResponse) VisitCreateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacterRequestObject struct {
	Id CharacterId `json:"id"`
}

type DeleteCharacterResponseObject interface {
	VisitDeleteCharacterResponse(w http.ResponseWriter) error
}

type DeleteCharacter204Response struct {
}

func (response DeleteCharacter204Response) VisitDeleteCharacterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCharacter401JSONResponse struct{ NoSessionJSONResponse }

func (response DeleteCharacter401JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacter404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteCharacter404JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCharacter409JSONResponse Error

func (response DeleteCharacter409JSONResponse) VisitDeleteCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacterRequestObject struct {
	Id   CharacterId `json:"id"`
	Body *UpdateCharacterJSONRequestBody
}

type UpdateCharacterResponseObject interface {
	VisitUpdateCharacterResponse(w http.ResponseWriter) error
}

type UpdateCharacter200JSONResponse Character

func (response UpdateCharacter200JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter401JSONResponse struct{ NoSessionJSONResponse }

func (response UpdateCharacter401JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateCharacter404JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter409JSONResponse Error

func (response UpdateCharacter409JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCharacter422JSONResponse struct{ InvalidJSONResponse }

func (response UpdateCharacter422JSONResponse) VisitUpdateCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SetMainCharacterRequestObject struct {
	Id CharacterId `json:"id"`
}

type SetMainCharacterResponseObject interface {
	VisitSetMainCharacterResponse(w http.ResponseWriter) error
}

type SetMainCharacter204Response struct {
}

func (response SetMainCharacter204Response) VisitSetMainCharacterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SetMainCharacter401JSONResponse struct{ NoSessionJSONResponse }

func (response SetMainCharacter401JSONResponse) VisitSetMainCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetMainCharacter404JSONResponse struct{ NotFoundJSONResponse }

func (response SetMainCharacter404JSONResponse) VisitSetMainCharacterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListClassesRequestObject struct {
}

type ListClassesResponseObject interface {
	VisitListClassesResponse(w http.ResponseWriter) error
}

type ListClasses200JSONResponse []Class

func (response ListClasses200JSONResponse) VisitListClassesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse Health

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstancesRequestObject struct {
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse []Instance

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLobbiesRequestObject struct {
	Params ListLobbiesParams
}

type ListLobbiesResponseObject interface {
	VisitListLobbiesResponse(w http.ResponseWriter) error
}

type ListLobbies200JSONResponse []Lobby

func (response ListLobbies200JSONResponse) VisitListLobbiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLobbies400JSONResponse Error

func (response ListLobbies400JSONResponse) VisitListLobbiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLobbyRequestObject struct {
	Body *CreateLobbyJSONRequestBody
}

type CreateLobbyResponseObject interface {
	VisitCreateLobbyResponse(w http.ResponseWriter) error
}

type CreateLobby201JSONResponse Lobby

func (response CreateLobby201JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLobby401JSONResponse struct{ NoSessionJSONResponse }

func (response CreateLobby401JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLobby409JSONResponse Error

func (response CreateLobby409JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLobby422JSONResponse struct{ InvalidJSONResponse }

func (response CreateLobby422JSONResponse) VisitCreateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetLobbyRequestObject struct {
	Id LobbyId `json:"id"`
}

type GetLobbyResponseObject interface {
	VisitGetLobbyResponse(w http.ResponseWriter) error
}

type GetLobby200JSONResponse Lobby

func (response GetLobby200JSONResponse) VisitGetLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLobby404JSONResponse struct{ LobbyNotFoundJSONResponse }

func (response GetLobby404JSONResponse) VisitGetLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLobbyRequestObject struct {
	Id   LobbyId `json:"id"`
	Body *UpdateLobbyJSONRequestBody
}

type UpdateLobbyResponseObject interface {
	VisitUpdateLobbyResponse(w http.ResponseWriter) error
}

type UpdateLobby200JSONResponse Lobby

func (response UpdateLobby200JSONResponse) VisitUpdateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLobby401JSONResponse struct{ NoSessionJSONResponse }

func (response UpdateLobby401JSONResponse) VisitUpdateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLobby404JSONResponse struct{ LobbyNotFoundJSONResponse }

func (response UpdateLobby404JSONResponse) VisitUpdateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLobby409JSONResponse struct{ LobbyNotOpenJSONResponse }

func (response UpdateLobby409JSONResponse) VisitUpdateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLobby422JSONResponse struct{ InvalidJSONResponse }

func (response UpdateLobby422JSONResponse) VisitUpdateLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLobbyRequestObject struct {
	Id   LobbyId `json:"id"`
	Body *CancelLobbyJSONRequestBody
}

type CancelLobbyResponseObject interface {
	VisitCancelLobbyResponse(w http.ResponseWriter) error
}

type CancelLobby200JSONResponse Lobby

func (response CancelLobby200JSONResponse) VisitCancelLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLobby401JSONResponse struct{ NoSessionJSONResponse }

func (response CancelLobby401JSONResponse) VisitCancelLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLobby404JSONResponse struct{ LobbyNotFoundJSONResponse }

func (response CancelLobby404JSONResponse) VisitCancelLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLobby409JSONResponse struct{ LobbyNotOpenJSONResponse }

func (response CancelLobby409JSONResponse) VisitCancelLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLobby422JSONResponse struct{ InvalidJSONResponse }

func (response CancelLobby422JSONResponse) VisitCancelLobbyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse Error

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateSessionFromDiscord Troca o código do Discord por uma sessão
	// (POST /auth/discord)
	CreateSessionFromDiscord(ctx context.Context, request CreateSessionFromDiscordRequestObject) (CreateSessionFromDiscordResponseObject, error)
	// ListCharacters Personagens do Usuário da sessão
	// (GET /characters)
	ListCharacters(ctx context.Context, request ListCharactersRequestObject) (ListCharactersResponseObject, error)
	// CreateCharacter Cadastra um personagem
	// (POST /characters)
	CreateCharacter(ctx context.Context, request CreateCharacterRequestObject) (CreateCharacterResponseObject, error)
	// DeleteCharacter Exclui um personagem
	// (DELETE /characters/{id})
	DeleteCharacter(ctx context.Context, request DeleteCharacterRequestObject) (DeleteCharacterResponseObject, error)
	// UpdateCharacter Edita um personagem
	// (PUT /characters/{id})
	UpdateCharacter(ctx context.Context, request UpdateCharacterRequestObject) (UpdateCharacterResponseObject, error)
	// SetMainCharacter Torna o personagem o principal
	// (PUT /characters/{id}/main)
	SetMainCharacter(ctx context.Context, request SetMainCharacterRequestObject) (SetMainCharacterResponseObject, error)
	// ListClasses Catálogo de classes
	// (GET /classes)
	ListClasses(ctx context.Context, request ListClassesRequestObject) (ListClassesResponseObject, error)
	// GetHealthz Estado da API e do banco
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// ListInstances Catálogo de instâncias
	// (GET /instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// ListLobbies Lobbies abertos num intervalo de dias
	// (GET /lobbies)
	ListLobbies(ctx context.Context, request ListLobbiesRequestObject) (ListLobbiesResponseObject, error)
	// CreateLobby Cria um lobby
	// (POST /lobbies)
	CreateLobby(ctx context.Context, request CreateLobbyRequestObject) (CreateLobbyResponseObject, error)
	// GetLobby Detalhe do lobby
	// (GET /lobbies/{id})
	GetLobby(ctx context.Context, request GetLobbyRequestObject) (GetLobbyResponseObject, error)
	// UpdateLobby Edita o lobby
	// (PUT /lobbies/{id})
	UpdateLobby(ctx context.Context, request UpdateLobbyRequestObject) (UpdateLobbyResponseObject, error)
	// CancelLobby Cancela o lobby
	// (POST /lobbies/{id}/cancel)
	CancelLobby(ctx context.Context, request CancelLobbyRequestObject) (CancelLobbyResponseObject, error)
	// GetMe Usuário da sessão
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// DeleteSession Encerra a sessão atual
	// (DELETE /session)
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateSessionFromDiscord operation middleware
func (sh *strictHandler) CreateSessionFromDiscord(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionFromDiscordRequestObject

	var body CreateSessionFromDiscordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSessionFromDiscord(ctx, request.(CreateSessionFromDiscordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSessionFromDiscord")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionFromDiscordResponseObject); ok {
		if err := validResponse.VisitCreateSessionFromDiscordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCharacters operation middleware
func (sh *strictHandler) ListCharacters(w http.ResponseWriter, r *http.Request) {
	var request ListCharactersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCharacters(ctx, request.(ListCharactersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCharacters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCharactersResponseObject); ok {
		if err := validResponse.VisitListCharactersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCharacter operation middleware
func (sh *strictHandler) CreateCharacter(w http.ResponseWriter, r *http.Request) {
	var request CreateCharacterRequestObject

	var body CreateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCharacter(ctx, request.(CreateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCharacterResponseObject); ok {
		if err := validResponse.VisitCreateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCharacter operation middleware
func (sh *strictHandler) DeleteCharacter(w http.ResponseWriter, r *http.Request, id CharacterId) {
	var request DeleteCharacterRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCharacter(ctx, request.(DeleteCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCharacterResponseObject); ok {
		if err := validResponse.VisitDeleteCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCharacter operation middleware
func (sh *strictHandler) UpdateCharacter(w http.ResponseWriter, r *http.Request, id CharacterId) {
	var request UpdateCharacterRequestObject

	request.Id = id

	var body UpdateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCharacter(ctx, request.(UpdateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCharacterResponseObject); ok {
		if err := validResponse.VisitUpdateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetMainCharacter operation middleware
func (sh *strictHandler) SetMainCharacter(w http.ResponseWriter, r *http.Request, id CharacterId) {
	var request SetMainCharacterRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetMainCharacter(ctx, request.(SetMainCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetMainCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetMainCharacterResponseObject); ok {
		if err := validResponse.VisitSetMainCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListClasses operation middleware
func (sh *strictHandler) ListClasses(w http.ResponseWriter, r *http.Request) {
	var request ListClassesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClasses(ctx, request.(ListClassesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClasses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClassesResponseObject); ok {
		if err := validResponse.VisitListClassesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(w http.ResponseWriter, r *http.Request) {
	var request ListInstancesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx, request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		if err := validResponse.VisitListInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLobbies operation middleware
func (sh *strictHandler) ListLobbies(w http.ResponseWriter, r *http.Request, params ListLobbiesParams) {
	var request ListLobbiesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLobbies(ctx, request.(ListLobbiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLobbies")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLobbiesResponseObject); ok {
		if err := validResponse.VisitListLobbiesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLobby operation middleware
func (sh *strictHandler) CreateLobby(w http.ResponseWriter, r *http.Request) {
	var request CreateLobbyRequestObject

	var body CreateLobbyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLobby(ctx, request.(CreateLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLobbyResponseObject); ok {
		if err := validResponse.VisitCreateLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLobby operation middleware
func (sh *strictHandler) GetLobby(w http.ResponseWriter, r *http.Request, id LobbyId) {
	var request GetLobbyRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLobby(ctx, request.(GetLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLobbyResponseObject); ok {
		if err := validResponse.VisitGetLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateLobby operation middleware
func (sh *strictHandler) UpdateLobby(w http.ResponseWriter, r *http.Request, id LobbyId) {
	var request UpdateLobbyRequestObject

	request.Id = id

	var body UpdateLobbyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateLobby(ctx, request.(UpdateLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateLobbyResponseObject); ok {
		if err := validResponse.VisitUpdateLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelLobby operation middleware
func (sh *strictHandler) CancelLobby(w http.ResponseWriter, r *http.Request, id LobbyId) {
	var request CancelLobbyRequestObject

	request.Id = id

	var body CancelLobbyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelLobby(ctx, request.(CancelLobbyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelLobby")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelLobbyResponseObject); ok {
		if err := validResponse.VisitCancelLobbyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request) {
	var request DeleteSessionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
