// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (lobby_id, user_id, character_id, role, message, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6)
RETURNING id, lobby_id, user_id, character_id, role, message, status, reason, created_at, decided_at
`

type CreateApplicationParams struct {
	LobbyID     pgtype.UUID
	UserID      pgtype.UUID
	CharacterID pgtype.UUID
	Role        string
	Message     pgtype.Text
	Now         time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.LobbyID,
		arg.UserID,
		arg.CharacterID,
		arg.Role,
		arg.Message,
		arg.Now,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.LobbyID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const expirePendingForLobby = `-- name: ExpirePendingForLobby :many
UPDATE applications SET status = 'expired', decided_at = $1::timestamptz
WHERE lobby_id = $2 AND status = 'pending'
RETURNING id
`

type ExpirePendingForLobbyParams struct {
	Now     time.Time
	LobbyID pgtype.UUID
}

// RN-16: no cancelamento, as pendentes expiram.
func (q *Queries) ExpirePendingForLobby(ctx context.Context, arg ExpirePendingForLobbyParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, expirePendingForLobby, arg.Now, arg.LobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationForUpdate = `-- name: GetApplicationForUpdate :one
SELECT id, lobby_id, user_id, character_id, role, message, status, reason, created_at, decided_at FROM applications WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetApplicationForUpdate(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationForUpdate, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.LobbyID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getUserApplicationInLobby = `-- name: GetUserApplicationInLobby :one
SELECT id, lobby_id, user_id, character_id, role, message, status, reason, created_at, decided_at FROM applications
WHERE lobby_id = $1 AND user_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetUserApplicationInLobbyParams struct {
	LobbyID pgtype.UUID
	UserID  pgtype.UUID
}

// A candidatura mais recente do Usuário no lobby (a "minha candidatura" do detalhe).
func (q *Queries) GetUserApplicationInLobby(ctx context.Context, arg GetUserApplicationInLobbyParams) (Application, error) {
	row := q.db.QueryRow(ctx, getUserApplicationInLobby, arg.LobbyID, arg.UserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.LobbyID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const hasActiveApplication = `-- name: HasActiveApplication :one
SELECT EXISTS (
    SELECT 1 FROM applications
    WHERE lobby_id = $1 AND user_id = $2 AND status IN ('pending', 'accepted')
)
`

type HasActiveApplicationParams struct {
	LobbyID pgtype.UUID
	UserID  pgtype.UUID
}

// RN-02: candidatura pendente ou aceita do Usuário no lobby.
func (q *Queries) HasActiveApplication(ctx context.Context, arg HasActiveApplicationParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveApplication, arg.LobbyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertApplicationEvent = `-- name: InsertApplicationEvent :exec
INSERT INTO application_events (application_id, from_status, to_status, actor_id, reason, at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertApplicationEventParams struct {
	ApplicationID pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	ActorID       pgtype.UUID
	Reason        pgtype.Text
	Now           time.Time
}

// RN-18: histórico de transições.
func (q *Queries) InsertApplicationEvent(ctx context.Context, arg InsertApplicationEventParams) error {
	_, err := q.db.Exec(ctx, insertApplicationEvent,
		arg.ApplicationID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Reason,
		arg.Now,
	)
	return err
}

const listApplicationEvents = `-- name: ListApplicationEvents :many
SELECT id, application_id, from_status, to_status, actor_id, reason, at FROM application_events WHERE application_id = $1 ORDER BY at, id
`

func (q *Queries) ListApplicationEvents(ctx context.Context, applicationID pgtype.UUID) ([]ApplicationEvent, error) {
	rows, err := q.db.Query(ctx, listApplicationEvents, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationEvent
	for rows.Next() {
		var i ApplicationEvent
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.Reason,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLobbyApplications = `-- name: ListLobbyApplications :many
SELECT applications.id, applications.lobby_id, applications.user_id, applications.character_id, applications.role, applications.message, applications.status, applications.reason, applications.created_at, applications.decided_at,
       c.nick, c.class_id, c.level, c.portrait, c.link,
       u.username, u.global_name
FROM applications
JOIN users u ON u.id = applications.user_id
LEFT JOIN characters c ON c.id = applications.character_id
WHERE applications.lobby_id = $1 AND applications.status IN ('pending', 'accepted')
ORDER BY applications.created_at, applications.id
`

type ListLobbyApplicationsRow struct {
	Application Application
	Nick        pgtype.Text
	ClassID     pgtype.Text
	Level       pgtype.Int2
	Portrait    pgtype.Text
	Link        pgtype.Text
	Username    string
	GlobalName  pgtype.Text
}

// Candidaturas ativas do lobby, com o personagem e o Discord (a visibilidade é do serviço).
func (q *Queries) ListLobbyApplications(ctx context.Context, lobbyID pgtype.UUID) ([]ListLobbyApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listLobbyApplications, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLobbyApplicationsRow
	for rows.Next() {
		var i ListLobbyApplicationsRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.LobbyID,
			&i.Application.UserID,
			&i.Application.CharacterID,
			&i.Application.Role,
			&i.Application.Message,
			&i.Application.Status,
			&i.Application.Reason,
			&i.Application.CreatedAt,
			&i.Application.DecidedAt,
			&i.Nick,
			&i.ClassID,
			&i.Level,
			&i.Portrait,
			&i.Link,
			&i.Username,
			&i.GlobalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyApplications = `-- name: ListMyApplications :many
SELECT applications.id, applications.lobby_id, applications.user_id, applications.character_id, applications.role, applications.message, applications.status, applications.reason, applications.created_at, applications.decided_at,
       l.instance_name, l.starts_at, l.cancelled_at AS lobby_cancelled_at,
       c.nick, c.class_id, c.level, c.portrait
FROM applications
JOIN lobbies l ON l.id = applications.lobby_id
LEFT JOIN characters c ON c.id = applications.character_id
WHERE applications.user_id = $1
ORDER BY applications.created_at DESC, applications.id DESC
`

type ListMyApplicationsRow struct {
	Application      Application
	InstanceName     string
	StartsAt         time.Time
	LobbyCancelledAt pgtype.Timestamptz
	Nick             pgtype.Text
	ClassID          pgtype.Text
	Level            pgtype.Int2
	Portrait         pgtype.Text
}

// RN-33: candidaturas do Usuário, com o lobby e o personagem, as mais recentes primeiro.
func (q *Queries) ListMyApplications(ctx context.Context, userID pgtype.UUID) ([]ListMyApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listMyApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyApplicationsRow
	for rows.Next() {
		var i ListMyApplicationsRow
		if err := rows.Scan(
			&i.Application.ID,
			&i.Application.LobbyID,
			&i.Application.UserID,
			&i.Application.CharacterID,
			&i.Application.Role,
			&i.Application.Message,
			&i.Application.Status,
			&i.Application.Reason,
			&i.Application.CreatedAt,
			&i.Application.DecidedAt,
			&i.InstanceName,
			&i.StartsAt,
			&i.LobbyCancelledAt,
			&i.Nick,
			&i.ClassID,
			&i.Level,
			&i.Portrait,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLobby = `-- name: LockLobby :one
SELECT id FROM lobbies WHERE id = $1 FOR UPDATE
`

// D-05: trava o lobby no aceite, depois do Usuário do candidato.
func (q *Queries) LockLobby(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockLobby, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const setApplicationStatus = `-- name: SetApplicationStatus :one
UPDATE applications
SET status = $1, reason = $2, decided_at = $3::timestamptz
WHERE id = $4
RETURNING id, lobby_id, user_id, character_id, role, message, status, reason, created_at, decided_at
`

type SetApplicationStatusParams struct {
	Status string
	Reason pgtype.Text
	Now    time.Time
	ID     pgtype.UUID
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationStatus,
		arg.Status,
		arg.Reason,
		arg.Now,
		arg.ID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.LobbyID,
		&i.UserID,
		&i.CharacterID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const wasRejected = `-- name: WasRejected :one
SELECT EXISTS (
    SELECT 1 FROM applications
    WHERE lobby_id = $1 AND user_id = $2 AND status = 'rejected'
)
`

type WasRejectedParams struct {
	LobbyID pgtype.UUID
	UserID  pgtype.UUID
}

// RN-07: recusado não se candidata de novo ao mesmo lobby.
func (q *Queries) WasRejected(ctx context.Context, arg WasRejectedParams) (bool, error) {
	row := q.db.QueryRow(ctx, wasRejected, arg.LobbyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
