// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMain = `-- name: ClearMain :exec
UPDATE characters SET is_main = false WHERE user_id = $1 AND is_main
`

func (q *Queries) ClearMain(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMain, userID)
	return err
}

const countCharacters = `-- name: CountCharacters :one
SELECT count(*) FROM characters WHERE user_id = $1
`

func (q *Queries) CountCharacters(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCharacters, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (user_id, nick, class_id, level, role, portrait, link, is_main, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, seq, user_id, nick, class_id, level, role, portrait, link, is_main, created_at
`

type CreateCharacterParams struct {
	UserID   pgtype.UUID
	Nick     string
	ClassID  string
	Level    int16
	Role     string
	Portrait string
	Link     pgtype.Text
	IsMain   bool
	Now      time.Time
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.UserID,
		arg.Nick,
		arg.ClassID,
		arg.Level,
		arg.Role,
		arg.Portrait,
		arg.Link,
		arg.IsMain,
		arg.Now,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.UserID,
		&i.Nick,
		&i.ClassID,
		&i.Level,
		&i.Role,
		&i.Portrait,
		&i.Link,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :one
DELETE FROM characters
WHERE id = $1 AND user_id = $2
RETURNING is_main
`

type DeleteCharacterParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Devolve se o excluído era o principal, para passar a vez ao mais antigo (RN-14).
func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) (bool, error) {
	row := q.db.QueryRow(ctx, deleteCharacter, arg.ID, arg.UserID)
	var is_main bool
	err := row.Scan(&is_main)
	return is_main, err
}

const getOwnCharacter = `-- name: GetOwnCharacter :one
SELECT id, seq, user_id, nick, class_id, level, role, portrait, link, is_main, created_at FROM characters WHERE id = $1 AND user_id = $2
`

type GetOwnCharacterParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Personagem do próprio Usuário (RN-08 da spec lobbies); de outro Usuário não volta nada.
func (q *Queries) GetOwnCharacter(ctx context.Context, arg GetOwnCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, getOwnCharacter, arg.ID, arg.UserID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.UserID,
		&i.Nick,
		&i.ClassID,
		&i.Level,
		&i.Role,
		&i.Portrait,
		&i.Link,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, seq, user_id, nick, class_id, level, role, portrait, link, is_main, created_at FROM characters
WHERE user_id = $1
ORDER BY is_main DESC, created_at, seq
`

// RN-17: o principal primeiro, depois por ordem de cadastro.
func (q *Queries) ListCharacters(ctx context.Context, userID pgtype.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.UserID,
			&i.Nick,
			&i.ClassID,
			&i.Level,
			&i.Role,
			&i.Portrait,
			&i.Link,
			&i.IsMain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// D-06: trava o Usuário enquanto cria, exclui ou troca o principal, para o limite de 10
// e o principal único valerem com pedidos simultâneos.
func (q *Queries) LockUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUser, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const promoteOldest = `-- name: PromoteOldest :exec
UPDATE characters SET is_main = true
WHERE id = (
    SELECT c.id FROM characters c
    WHERE c.user_id = $1
    ORDER BY c.created_at, c.seq
    LIMIT 1
)
`

// RN-14: o personagem mais antigo que sobrou vira o principal.
func (q *Queries) PromoteOldest(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteOldest, userID)
	return err
}

const setMain = `-- name: SetMain :execrows
UPDATE characters SET is_main = true WHERE id = $1 AND user_id = $2
`

type SetMainParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SetMain(ctx context.Context, arg SetMainParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMain, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters
SET nick = $1, class_id = $2, level = $3, role = $4,
    portrait = $5, link = $6
WHERE id = $7 AND user_id = $8
RETURNING id, seq, user_id, nick, class_id, level, role, portrait, link, is_main, created_at
`

type UpdateCharacterParams struct {
	Nick     string
	ClassID  string
	Level    int16
	Role     string
	Portrait string
	Link     pgtype.Text
	ID       pgtype.UUID
	UserID   pgtype.UUID
}

// D-08: filtra pelo dono; personagem de outro Usuário não volta nada (RN-02).
func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter,
		arg.Nick,
		arg.ClassID,
		arg.Level,
		arg.Role,
		arg.Portrait,
		arg.Link,
		arg.ID,
		arg.UserID,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.UserID,
		&i.Nick,
		&i.ClassID,
		&i.Level,
		&i.Role,
		&i.Portrait,
		&i.Link,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}
