// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobbies.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLobby = `-- name: CancelLobby :exec
UPDATE lobbies SET cancelled_at = $1::timestamptz, cancel_reason = $2::text WHERE id = $3
`

type CancelLobbyParams struct {
	Now    time.Time
	Reason string
	ID     pgtype.UUID
}

func (q *Queries) CancelLobby(ctx context.Context, arg CancelLobbyParams) error {
	_, err := q.db.Exec(ctx, cancelLobby, arg.Now, arg.Reason, arg.ID)
	return err
}

const characterInOpenLobby = `-- name: CharacterInOpenLobby :one
SELECT EXISTS (
    SELECT 1 FROM lobbies l
    WHERE l.cancelled_at IS NULL AND l.starts_at > $1
      AND (l.owner_character_id = $2
           OR EXISTS (SELECT 1 FROM applications a
                      WHERE a.lobby_id = l.id AND a.character_id = $2
                        AND a.status IN ('pending', 'accepted'))
           OR EXISTS (SELECT 1 FROM swap_requests r
                      JOIN applications a ON a.id = r.application_id
                      WHERE a.lobby_id = l.id AND r.to_character_id = $2
                        AND r.status = 'pending'))
)
`

type CharacterInOpenLobbyParams struct {
	Now         time.Time
	CharacterID pgtype.UUID
}

// RN-21 da lobbies e RN-25/RN-26 da candidatura: o personagem é dono de um lobby aberto,
// tem candidatura pendente ou aceita num lobby aberto, ou é o personagem novo de um pedido
// de troca pendente num lobby aberto.
func (q *Queries) CharacterInOpenLobby(ctx context.Context, arg CharacterInOpenLobbyParams) (bool, error) {
	row := q.db.QueryRow(ctx, characterInOpenLobby, arg.Now, arg.CharacterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countOpenLobbiesByOwner = `-- name: CountOpenLobbiesByOwner :one
SELECT count(*) FROM lobbies
WHERE owner_id = $1 AND cancelled_at IS NULL AND starts_at > $2
`

type CountOpenLobbiesByOwnerParams struct {
	OwnerID pgtype.UUID
	Now     time.Time
}

// RN-11: lobbies abertos do Usuário como dono.
func (q *Queries) CountOpenLobbiesByOwner(ctx context.Context, arg CountOpenLobbiesByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenLobbiesByOwner, arg.OwnerID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (owner_id, instance_id, instance_name, instance_level, starts_at,
    slots_tank, slots_support, slots_dps, min_level, owner_character_id, owner_role, note, created_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type CreateLobbyParams struct {
	OwnerID          pgtype.UUID
	InstanceID       string
	InstanceName     string
	InstanceLevel    int16
	StartsAt         time.Time
	SlotsTank        int16
	SlotsSupport     int16
	SlotsDps         int16
	MinLevel         int16
	OwnerCharacterID pgtype.UUID
	OwnerRole        string
	Note             pgtype.Text
	Now              time.Time
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createLobby,
		arg.OwnerID,
		arg.InstanceID,
		arg.InstanceName,
		arg.InstanceLevel,
		arg.StartsAt,
		arg.SlotsTank,
		arg.SlotsSupport,
		arg.SlotsDps,
		arg.MinLevel,
		arg.OwnerCharacterID,
		arg.OwnerRole,
		arg.Note,
		arg.Now,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLobby = `-- name: GetLobby :one
SELECT lobbies.id, lobbies.owner_id, lobbies.instance_id, lobbies.instance_name, lobbies.instance_level, lobbies.starts_at, lobbies.slots_tank, lobbies.slots_support, lobbies.slots_dps, lobbies.min_level, lobbies.owner_character_id, lobbies.owner_role, lobbies.note, lobbies.cancelled_at, lobbies.cancel_reason, lobbies.created_at,
       c.nick AS owner_nick, c.class_id AS owner_class_id, c.level AS owner_level, c.portrait AS owner_portrait, c.link AS owner_link,
       u.username AS owner_username, u.global_name AS owner_global_name,
       -- D-03 (candidatura): membros aceitos por função e pendentes.
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'tank') AS accepted_tank,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'support') AS accepted_support,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'dps') AS accepted_dps,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'pending') AS pending_count
FROM lobbies
JOIN users u ON u.id = lobbies.owner_id
LEFT JOIN characters c ON c.id = lobbies.owner_character_id
WHERE lobbies.id = $1
`

type GetLobbyRow struct {
	Lobby           Lobby
	OwnerNick       pgtype.Text
	OwnerClassID    pgtype.Text
	OwnerLevel      pgtype.Int2
	OwnerPortrait   pgtype.Text
	OwnerLink       pgtype.Text
	OwnerUsername   string
	OwnerGlobalName pgtype.Text
	AcceptedTank    int64
	AcceptedSupport int64
	AcceptedDps     int64
	PendingCount    int64
}

// RN-15: o lobby em qualquer estado, com o personagem e o Discord do dono.
func (q *Queries) GetLobby(ctx context.Context, id pgtype.UUID) (GetLobbyRow, error) {
	row := q.db.QueryRow(ctx, getLobby, id)
	var i GetLobbyRow
	err := row.Scan(
		&i.Lobby.ID,
		&i.Lobby.OwnerID,
		&i.Lobby.InstanceID,
		&i.Lobby.InstanceName,
		&i.Lobby.InstanceLevel,
		&i.Lobby.StartsAt,
		&i.Lobby.SlotsTank,
		&i.Lobby.SlotsSupport,
		&i.Lobby.SlotsDps,
		&i.Lobby.MinLevel,
		&i.Lobby.OwnerCharacterID,
		&i.Lobby.OwnerRole,
		&i.Lobby.Note,
		&i.Lobby.CancelledAt,
		&i.Lobby.CancelReason,
		&i.Lobby.CreatedAt,
		&i.OwnerNick,
		&i.OwnerClassID,
		&i.OwnerLevel,
		&i.OwnerPortrait,
		&i.OwnerLink,
		&i.OwnerUsername,
		&i.OwnerGlobalName,
		&i.AcceptedTank,
		&i.AcceptedSupport,
		&i.AcceptedDps,
		&i.PendingCount,
	)
	return i, err
}

const getOwnLobbyForUpdate = `-- name: GetOwnLobbyForUpdate :one
SELECT id, owner_id, instance_id, instance_name, instance_level, starts_at, slots_tank, slots_support, slots_dps, min_level, owner_character_id, owner_role, note, cancelled_at, cancel_reason, created_at FROM lobbies WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type GetOwnLobbyForUpdateParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// RN-20 / D-08: só o lobby do próprio Usuário, travado para editar ou cancelar.
func (q *Queries) GetOwnLobbyForUpdate(ctx context.Context, arg GetOwnLobbyForUpdateParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, getOwnLobbyForUpdate, arg.ID, arg.OwnerID)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.InstanceID,
		&i.InstanceName,
		&i.InstanceLevel,
		&i.StartsAt,
		&i.SlotsTank,
		&i.SlotsSupport,
		&i.SlotsDps,
		&i.MinLevel,
		&i.OwnerCharacterID,
		&i.OwnerRole,
		&i.Note,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const hasScheduleConflict = `-- name: HasScheduleConflict :one
SELECT EXISTS (
    SELECT 1 FROM lobbies l
    WHERE l.cancelled_at IS NULL
      AND l.id IS DISTINCT FROM $1
      AND l.starts_at > $2
      AND l.starts_at < $3
      AND (l.owner_character_id = $4
           OR EXISTS (SELECT 1 FROM applications a
                      WHERE a.lobby_id = l.id AND a.character_id = $4
                        AND a.status = 'accepted'))
)
`

type HasScheduleConflictParams struct {
	ExcludeID   pgtype.UUID
	WindowStart time.Time
	WindowEnd   time.Time
	CharacterID pgtype.UUID
}

// RN-10 da lobbies e RN-11 da candidatura (D-03 e D-04): outro lobby não cancelado, com
// início dentro da janela (início - 2 h, início + 2 h) calculada pelo serviço, em que o
// personagem é dono ou membro aceito.
func (q *Queries) HasScheduleConflict(ctx context.Context, arg HasScheduleConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasScheduleConflict,
		arg.ExcludeID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.CharacterID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOpenLobbies = `-- name: ListOpenLobbies :many
SELECT lobbies.id, lobbies.owner_id, lobbies.instance_id, lobbies.instance_name, lobbies.instance_level, lobbies.starts_at, lobbies.slots_tank, lobbies.slots_support, lobbies.slots_dps, lobbies.min_level, lobbies.owner_character_id, lobbies.owner_role, lobbies.note, lobbies.cancelled_at, lobbies.cancel_reason, lobbies.created_at,
       c.nick AS owner_nick, c.class_id AS owner_class_id, c.level AS owner_level, c.portrait AS owner_portrait, c.link AS owner_link,
       u.username AS owner_username, u.global_name AS owner_global_name,
       -- D-03 (candidatura): membros aceitos por função e pendentes.
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'tank') AS accepted_tank,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'support') AS accepted_support,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'accepted' AND a.role = 'dps') AS accepted_dps,
       (SELECT count(*) FROM applications a WHERE a.lobby_id = lobbies.id AND a.status = 'pending') AS pending_count
FROM lobbies
JOIN users u ON u.id = lobbies.owner_id
LEFT JOIN characters c ON c.id = lobbies.owner_character_id
WHERE lobbies.cancelled_at IS NULL
  AND lobbies.starts_at > $1
  AND lobbies.starts_at >= $2
  AND lobbies.starts_at < $3
ORDER BY lobbies.starts_at, lobbies.created_at, lobbies.id
`

type ListOpenLobbiesParams struct {
	Now    time.Time
	FromAt time.Time
	ToAt   time.Time
}

type ListOpenLobbiesRow struct {
	Lobby           Lobby
	OwnerNick       pgtype.Text
	OwnerClassID    pgtype.Text
	OwnerLevel      pgtype.Int2
	OwnerPortrait   pgtype.Text
	OwnerLink       pgtype.Text
	OwnerUsername   string
	OwnerGlobalName pgtype.Text
	AcceptedTank    int64
	AcceptedSupport int64
	AcceptedDps     int64
	PendingCount    int64
}

// RN-13 / RN-14: só abertos (não cancelados e ainda não iniciados), por início.
func (q *Queries) ListOpenLobbies(ctx context.Context, arg ListOpenLobbiesParams) ([]ListOpenLobbiesRow, error) {
	rows, err := q.db.Query(ctx, listOpenLobbies, arg.Now, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenLobbiesRow
	for rows.Next() {
		var i ListOpenLobbiesRow
		if err := rows.Scan(
			&i.Lobby.ID,
			&i.Lobby.OwnerID,
			&i.Lobby.InstanceID,
			&i.Lobby.InstanceName,
			&i.Lobby.InstanceLevel,
			&i.Lobby.StartsAt,
			&i.Lobby.SlotsTank,
			&i.Lobby.SlotsSupport,
			&i.Lobby.SlotsDps,
			&i.Lobby.MinLevel,
			&i.Lobby.OwnerCharacterID,
			&i.Lobby.OwnerRole,
			&i.Lobby.Note,
			&i.Lobby.CancelledAt,
			&i.Lobby.CancelReason,
			&i.Lobby.CreatedAt,
			&i.OwnerNick,
			&i.OwnerClassID,
			&i.OwnerLevel,
			&i.OwnerPortrait,
			&i.OwnerLink,
			&i.OwnerUsername,
			&i.OwnerGlobalName,
			&i.AcceptedTank,
			&i.AcceptedSupport,
			&i.AcceptedDps,
			&i.PendingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLobbyOwnerCharacter = `-- name: SetLobbyOwnerCharacter :exec
UPDATE lobbies SET owner_character_id = $1, owner_role = $2 WHERE id = $3
`

type SetLobbyOwnerCharacterParams struct {
	CharacterID pgtype.UUID
	Role        string
	ID          pgtype.UUID
}

// RN-19 da candidatura: o dono troca o próprio personagem, e a vaga passa a ser da função
// do personagem novo.
func (q *Queries) SetLobbyOwnerCharacter(ctx context.Context, arg SetLobbyOwnerCharacterParams) error {
	_, err := q.db.Exec(ctx, setLobbyOwnerCharacter, arg.CharacterID, arg.Role, arg.ID)
	return err
}

const updateLobby = `-- name: UpdateLobby :exec
UPDATE lobbies
SET instance_id = $1, instance_name = $2, instance_level = $3,
    starts_at = $4, slots_tank = $5, slots_support = $6,
    slots_dps = $7, min_level = $8, note = $9
WHERE id = $10
`

type UpdateLobbyParams struct {
	InstanceID    string
	InstanceName  string
	InstanceLevel int16
	StartsAt      time.Time
	SlotsTank     int16
	SlotsSupport  int16
	SlotsDps      int16
	MinLevel      int16
	Note          pgtype.Text
	ID            pgtype.UUID
}

func (q *Queries) UpdateLobby(ctx context.Context, arg UpdateLobbyParams) error {
	_, err := q.db.Exec(ctx, updateLobby,
		arg.InstanceID,
		arg.InstanceName,
		arg.InstanceLevel,
		arg.StartsAt,
		arg.SlotsTank,
		arg.SlotsSupport,
		arg.SlotsDps,
		arg.MinLevel,
		arg.Note,
		arg.ID,
	)
	return err
}
