// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobbies.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLobby = `-- name: CancelLobby :exec
UPDATE lobbies SET cancelled_at = $1::timestamptz, cancel_reason = $2::text WHERE id = $3
`

type CancelLobbyParams struct {
	Now    time.Time
	Reason string
	ID     pgtype.UUID
}

func (q *Queries) CancelLobby(ctx context.Context, arg CancelLobbyParams) error {
	_, err := q.db.Exec(ctx, cancelLobby, arg.Now, arg.Reason, arg.ID)
	return err
}

const characterOwnsOpenLobby = `-- name: CharacterOwnsOpenLobby :one
SELECT EXISTS (
    SELECT 1 FROM lobbies
    WHERE owner_character_id = $1 AND cancelled_at IS NULL AND starts_at > $2
)
`

type CharacterOwnsOpenLobbyParams struct {
	CharacterID pgtype.UUID
	Now         time.Time
}

// RN-21: o personagem é dono de um lobby aberto.
func (q *Queries) CharacterOwnsOpenLobby(ctx context.Context, arg CharacterOwnsOpenLobbyParams) (bool, error) {
	row := q.db.QueryRow(ctx, characterOwnsOpenLobby, arg.CharacterID, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countOpenLobbiesByOwner = `-- name: CountOpenLobbiesByOwner :one
SELECT count(*) FROM lobbies
WHERE owner_id = $1 AND cancelled_at IS NULL AND starts_at > $2
`

type CountOpenLobbiesByOwnerParams struct {
	OwnerID pgtype.UUID
	Now     time.Time
}

// RN-11: lobbies abertos do Usuário como dono.
func (q *Queries) CountOpenLobbiesByOwner(ctx context.Context, arg CountOpenLobbiesByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenLobbiesByOwner, arg.OwnerID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (owner_id, instance_id, instance_name, instance_level, starts_at,
    slots_tank, slots_support, slots_dps, min_level, owner_character_id, owner_role, note, created_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type CreateLobbyParams struct {
	OwnerID          pgtype.UUID
	InstanceID       string
	InstanceName     string
	InstanceLevel    int16
	StartsAt         time.Time
	SlotsTank        int16
	SlotsSupport     int16
	SlotsDps         int16
	MinLevel         int16
	OwnerCharacterID pgtype.UUID
	OwnerRole        string
	Note             pgtype.Text
	Now              time.Time
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createLobby,
		arg.OwnerID,
		arg.InstanceID,
		arg.InstanceName,
		arg.InstanceLevel,
		arg.StartsAt,
		arg.SlotsTank,
		arg.SlotsSupport,
		arg.SlotsDps,
		arg.MinLevel,
		arg.OwnerCharacterID,
		arg.OwnerRole,
		arg.Note,
		arg.Now,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLobby = `-- name: GetLobby :one
SELECT lobbies.id, lobbies.owner_id, lobbies.instance_id, lobbies.instance_name, lobbies.instance_level, lobbies.starts_at, lobbies.slots_tank, lobbies.slots_support, lobbies.slots_dps, lobbies.min_level, lobbies.owner_character_id, lobbies.owner_role, lobbies.note, lobbies.cancelled_at, lobbies.cancel_reason, lobbies.created_at,
       c.nick AS owner_nick, c.class_id AS owner_class_id, c.level AS owner_level, c.portrait AS owner_portrait,
       u.username AS owner_username, u.global_name AS owner_global_name
FROM lobbies
JOIN users u ON u.id = lobbies.owner_id
LEFT JOIN characters c ON c.id = lobbies.owner_character_id
WHERE lobbies.id = $1
`

type GetLobbyRow struct {
	Lobby           Lobby
	OwnerNick       pgtype.Text
	OwnerClassID    pgtype.Text
	OwnerLevel      pgtype.Int2
	OwnerPortrait   pgtype.Text
	OwnerUsername   string
	OwnerGlobalName pgtype.Text
}

// RN-15: o lobby em qualquer estado, com o personagem e o Discord do dono.
func (q *Queries) GetLobby(ctx context.Context, id pgtype.UUID) (GetLobbyRow, error) {
	row := q.db.QueryRow(ctx, getLobby, id)
	var i GetLobbyRow
	err := row.Scan(
		&i.Lobby.ID,
		&i.Lobby.OwnerID,
		&i.Lobby.InstanceID,
		&i.Lobby.InstanceName,
		&i.Lobby.InstanceLevel,
		&i.Lobby.StartsAt,
		&i.Lobby.SlotsTank,
		&i.Lobby.SlotsSupport,
		&i.Lobby.SlotsDps,
		&i.Lobby.MinLevel,
		&i.Lobby.OwnerCharacterID,
		&i.Lobby.OwnerRole,
		&i.Lobby.Note,
		&i.Lobby.CancelledAt,
		&i.Lobby.CancelReason,
		&i.Lobby.CreatedAt,
		&i.OwnerNick,
		&i.OwnerClassID,
		&i.OwnerLevel,
		&i.OwnerPortrait,
		&i.OwnerUsername,
		&i.OwnerGlobalName,
	)
	return i, err
}

const getOwnLobbyForUpdate = `-- name: GetOwnLobbyForUpdate :one
SELECT id, owner_id, instance_id, instance_name, instance_level, starts_at, slots_tank, slots_support, slots_dps, min_level, owner_character_id, owner_role, note, cancelled_at, cancel_reason, created_at FROM lobbies WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type GetOwnLobbyForUpdateParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

// RN-20 / D-08: só o lobby do próprio Usuário, travado para editar ou cancelar.
func (q *Queries) GetOwnLobbyForUpdate(ctx context.Context, arg GetOwnLobbyForUpdateParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, getOwnLobbyForUpdate, arg.ID, arg.OwnerID)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.InstanceID,
		&i.InstanceName,
		&i.InstanceLevel,
		&i.StartsAt,
		&i.SlotsTank,
		&i.SlotsSupport,
		&i.SlotsDps,
		&i.MinLevel,
		&i.OwnerCharacterID,
		&i.OwnerRole,
		&i.Note,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
	)
	return i, err
}

const hasScheduleConflict = `-- name: HasScheduleConflict :one
SELECT EXISTS (
    SELECT 1 FROM lobbies
    WHERE owner_character_id = $1
      AND cancelled_at IS NULL
      AND id IS DISTINCT FROM $2
      AND starts_at > $3
      AND starts_at < $4
)
`

type HasScheduleConflictParams struct {
	CharacterID pgtype.UUID
	ExcludeID   pgtype.UUID
	WindowStart time.Time
	WindowEnd   time.Time
}

// RN-10 / D-03: outro lobby não cancelado do mesmo personagem com início dentro da
// janela (início - 2 h, início + 2 h), calculada pelo serviço.
func (q *Queries) HasScheduleConflict(ctx context.Context, arg HasScheduleConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasScheduleConflict,
		arg.CharacterID,
		arg.ExcludeID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOpenLobbies = `-- name: ListOpenLobbies :many
SELECT lobbies.id, lobbies.owner_id, lobbies.instance_id, lobbies.instance_name, lobbies.instance_level, lobbies.starts_at, lobbies.slots_tank, lobbies.slots_support, lobbies.slots_dps, lobbies.min_level, lobbies.owner_character_id, lobbies.owner_role, lobbies.note, lobbies.cancelled_at, lobbies.cancel_reason, lobbies.created_at,
       c.nick AS owner_nick, c.class_id AS owner_class_id, c.level AS owner_level, c.portrait AS owner_portrait,
       u.username AS owner_username, u.global_name AS owner_global_name
FROM lobbies
JOIN users u ON u.id = lobbies.owner_id
LEFT JOIN characters c ON c.id = lobbies.owner_character_id
WHERE lobbies.cancelled_at IS NULL
  AND lobbies.starts_at > $1
  AND lobbies.starts_at >= $2
  AND lobbies.starts_at < $3
ORDER BY lobbies.starts_at, lobbies.created_at, lobbies.id
`

type ListOpenLobbiesParams struct {
	Now    time.Time
	FromAt time.Time
	ToAt   time.Time
}

type ListOpenLobbiesRow struct {
	Lobby           Lobby
	OwnerNick       pgtype.Text
	OwnerClassID    pgtype.Text
	OwnerLevel      pgtype.Int2
	OwnerPortrait   pgtype.Text
	OwnerUsername   string
	OwnerGlobalName pgtype.Text
}

// RN-13 / RN-14: só abertos (não cancelados e ainda não iniciados), por início.
func (q *Queries) ListOpenLobbies(ctx context.Context, arg ListOpenLobbiesParams) ([]ListOpenLobbiesRow, error) {
	rows, err := q.db.Query(ctx, listOpenLobbies, arg.Now, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenLobbiesRow
	for rows.Next() {
		var i ListOpenLobbiesRow
		if err := rows.Scan(
			&i.Lobby.ID,
			&i.Lobby.OwnerID,
			&i.Lobby.InstanceID,
			&i.Lobby.InstanceName,
			&i.Lobby.InstanceLevel,
			&i.Lobby.StartsAt,
			&i.Lobby.SlotsTank,
			&i.Lobby.SlotsSupport,
			&i.Lobby.SlotsDps,
			&i.Lobby.MinLevel,
			&i.Lobby.OwnerCharacterID,
			&i.Lobby.OwnerRole,
			&i.Lobby.Note,
			&i.Lobby.CancelledAt,
			&i.Lobby.CancelReason,
			&i.Lobby.CreatedAt,
			&i.OwnerNick,
			&i.OwnerClassID,
			&i.OwnerLevel,
			&i.OwnerPortrait,
			&i.OwnerUsername,
			&i.OwnerGlobalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLobby = `-- name: UpdateLobby :exec
UPDATE lobbies
SET starts_at = $1, slots_tank = $2, slots_support = $3,
    slots_dps = $4, min_level = $5, note = $6
WHERE id = $7
`

type UpdateLobbyParams struct {
	StartsAt     time.Time
	SlotsTank    int16
	SlotsSupport int16
	SlotsDps     int16
	MinLevel     int16
	Note         pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) UpdateLobby(ctx context.Context, arg UpdateLobbyParams) error {
	_, err := q.db.Exec(ctx, updateLobby,
		arg.StartsAt,
		arg.SlotsTank,
		arg.SlotsSupport,
		arg.SlotsDps,
		arg.MinLevel,
		arg.Note,
		arg.ID,
	)
	return err
}
