// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID        pgtype.UUID
	Seq       int64
	UserID    pgtype.UUID
	Nick      string
	ClassID   string
	Level     int16
	Role      string
	Portrait  string
	Link      pgtype.Text
	IsMain    bool
	CreatedAt time.Time
}

type Lobby struct {
	ID               pgtype.UUID
	OwnerID          pgtype.UUID
	InstanceID       string
	InstanceName     string
	InstanceLevel    int16
	StartsAt         time.Time
	SlotsTank        int16
	SlotsSupport     int16
	SlotsDps         int16
	MinLevel         int16
	OwnerCharacterID pgtype.UUID
	OwnerRole        string
	Note             pgtype.Text
	CancelledAt      pgtype.Timestamptz
	CancelReason     pgtype.Text
	CreatedAt        time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     pgtype.UUID
	CreatedAt  time.Time
	LastUsedAt time.Time
}

type User struct {
	ID          pgtype.UUID
	DiscordID   string
	Username    string
	GlobalName  pgtype.Text
	CreatedAt   time.Time
	LastLoginAt time.Time
}
