// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID          pgtype.UUID
	LobbyID     pgtype.UUID
	UserID      pgtype.UUID
	CharacterID pgtype.UUID
	Role        string
	Message     pgtype.Text
	Status      string
	Reason      pgtype.Text
	CreatedAt   time.Time
	DecidedAt   pgtype.Timestamptz
	Blocked     bool
}

type ApplicationEvent struct {
	ID            int64
	ApplicationID pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	ActorID       pgtype.UUID
	Reason        pgtype.Text
	At            time.Time
}

type Character struct {
	ID        pgtype.UUID
	Seq       int64
	UserID    pgtype.UUID
	Nick      string
	ClassID   string
	Level     int16
	Role      string
	Portrait  string
	Link      pgtype.Text
	IsMain    bool
	CreatedAt time.Time
}

type CharacterAvailability struct {
	CharacterID pgtype.UUID
	Enabled     bool
	Days        int16
	StartMinute int16
	EndMinute   int16
	AnyInstance bool
	InstanceIds []string
	UpdatedAt   time.Time
}

type Lobby struct {
	ID               pgtype.UUID
	OwnerID          pgtype.UUID
	InstanceID       pgtype.Text
	InstanceName     pgtype.Text
	InstanceLevel    int16
	StartsAt         time.Time
	SlotsTank        int16
	SlotsSupport     int16
	SlotsDps         int16
	MinLevel         int16
	OwnerCharacterID pgtype.UUID
	OwnerRole        string
	Note             pgtype.Text
	CancelledAt      pgtype.Timestamptz
	CancelReason     pgtype.Text
	CreatedAt        time.Time
	Formation        string
	FreeSlots        pgtype.Int2
}

type Session struct {
	TokenHash  []byte
	UserID     pgtype.UUID
	CreatedAt  time.Time
	LastUsedAt time.Time
}

type SwapRequest struct {
	ID              pgtype.UUID
	ApplicationID   pgtype.UUID
	FromCharacterID pgtype.UUID
	ToCharacterID   pgtype.UUID
	ToRole          string
	Reason          string
	Status          string
	DecisionReason  pgtype.Text
	CreatedAt       time.Time
	DecidedAt       pgtype.Timestamptz
}

type SwapRequestEvent struct {
	ID            int64
	SwapRequestID pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	ActorID       pgtype.UUID
	Reason        pgtype.Text
	At            time.Time
}

type User struct {
	ID          pgtype.UUID
	DiscordID   string
	Username    string
	GlobalName  pgtype.Text
	CreatedAt   time.Time
	LastLoginAt time.Time
}
