// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
)

const sessionTimeZone = `-- name: SessionTimeZone :one
SELECT current_setting('TimeZone')::text AS time_zone
`

// Fuso da sessão atual, usado para conferir a RN-08.
func (q *Queries) SessionTimeZone(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, sessionTimeZone)
	var time_zone string
	err := row.Scan(&time_zone)
	return time_zone, err
}
