// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, last_used_at)
VALUES ($1, $2, $3, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Now       time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.Now)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

// RN-11: sair apaga só esta Sessão.
func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT users.id, users.discord_id, users.username, users.global_name, users.created_at, users.last_login_at, sessions.last_used_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.last_used_at > $2
`

type GetActiveSessionParams struct {
	TokenHash  []byte
	ValidAfter time.Time
}

type GetActiveSessionRow struct {
	User       User
	LastUsedAt time.Time
}

// RN-09 e RN-10: a Sessão vale enquanto o último uso for posterior a @valid_after
// (agora menos 30 dias). Vencida ou desconhecida, não volta nada.
func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.TokenHash, arg.ValidAfter)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.User.ID,
		&i.User.DiscordID,
		&i.User.Username,
		&i.User.GlobalName,
		&i.User.CreatedAt,
		&i.User.LastLoginAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_used_at = $1
WHERE token_hash = $2
  AND last_used_at < $3
`

type TouchSessionParams struct {
	Now         time.Time
	TokenHash   []byte
	StaleBefore time.Time
}

// RN-09: renova o último uso, mas só grava se o registrado for anterior a @stale_before
// (agora menos 1 hora).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.Now, arg.TokenHash, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
