// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: swap_requests.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSwapRequest = `-- name: CreateSwapRequest :one
INSERT INTO swap_requests (application_id, from_character_id, to_character_id, to_role, reason, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6)
RETURNING id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at
`

type CreateSwapRequestParams struct {
	ApplicationID   pgtype.UUID
	FromCharacterID pgtype.UUID
	ToCharacterID   pgtype.UUID
	ToRole          string
	Reason          string
	Now             time.Time
}

func (q *Queries) CreateSwapRequest(ctx context.Context, arg CreateSwapRequestParams) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, createSwapRequest,
		arg.ApplicationID,
		arg.FromCharacterID,
		arg.ToCharacterID,
		arg.ToRole,
		arg.Reason,
		arg.Now,
	)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const expirePendingSwapsForLobby = `-- name: ExpirePendingSwapsForLobby :many
UPDATE swap_requests SET status = 'expired', decided_at = $1::timestamptz
WHERE status = 'pending'
  AND application_id IN (SELECT id FROM applications WHERE lobby_id = $2)
RETURNING id
`

type ExpirePendingSwapsForLobbyParams struct {
	Now     time.Time
	LobbyID pgtype.UUID
}

// RN-16, D-12: no cancelamento, os pedidos pendentes expiram.
func (q *Queries) ExpirePendingSwapsForLobby(ctx context.Context, arg ExpirePendingSwapsForLobbyParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, expirePendingSwapsForLobby, arg.Now, arg.LobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSwapRequest = `-- name: GetLatestSwapRequest :one
SELECT id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at FROM swap_requests
WHERE application_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// O pedido mais recente da candidatura (o "meu pedido" do detalhe, D-12).
func (q *Queries) GetLatestSwapRequest(ctx context.Context, applicationID pgtype.UUID) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, getLatestSwapRequest, applicationID)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getPendingSwapRequest = `-- name: GetPendingSwapRequest :one
SELECT id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at FROM swap_requests
WHERE application_id = $1 AND status = 'pending'
FOR UPDATE
`

// RN-20: o pedido pendente da candidatura, se houver.
func (q *Queries) GetPendingSwapRequest(ctx context.Context, applicationID pgtype.UUID) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, getPendingSwapRequest, applicationID)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getSwapRequest = `-- name: GetSwapRequest :one
SELECT id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at FROM swap_requests WHERE id = $1
`

// Leitura sem trava, para descobrir o membro antes de travar (D-10).
func (q *Queries) GetSwapRequest(ctx context.Context, id pgtype.UUID) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, getSwapRequest, id)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getSwapRequestForUpdate = `-- name: GetSwapRequestForUpdate :one
SELECT id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at FROM swap_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSwapRequestForUpdate(ctx context.Context, id pgtype.UUID) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, getSwapRequestForUpdate, id)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertSwapRequestEvent = `-- name: InsertSwapRequestEvent :exec
INSERT INTO swap_request_events (swap_request_id, from_status, to_status, actor_id, reason, at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSwapRequestEventParams struct {
	SwapRequestID pgtype.UUID
	FromStatus    pgtype.Text
	ToStatus      string
	ActorID       pgtype.UUID
	Reason        pgtype.Text
	Now           time.Time
}

// RN-18: histórico de transições do pedido.
func (q *Queries) InsertSwapRequestEvent(ctx context.Context, arg InsertSwapRequestEventParams) error {
	_, err := q.db.Exec(ctx, insertSwapRequestEvent,
		arg.SwapRequestID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Reason,
		arg.Now,
	)
	return err
}

const listLobbySwapRequests = `-- name: ListLobbySwapRequests :many
SELECT swap_requests.id, swap_requests.application_id, swap_requests.from_character_id, swap_requests.to_character_id, swap_requests.to_role, swap_requests.reason, swap_requests.status, swap_requests.decision_reason, swap_requests.created_at, swap_requests.decided_at,
       a.user_id, a.role AS from_role,
       u.username, u.global_name,
       fc.nick AS from_nick, fc.class_id AS from_class_id, fc.level AS from_level,
       fc.portrait AS from_portrait,
       tc.nick AS to_nick, tc.class_id AS to_class_id, tc.level AS to_level,
       tc.portrait AS to_portrait
FROM swap_requests
JOIN applications a ON a.id = swap_requests.application_id
JOIN users u ON u.id = a.user_id
LEFT JOIN characters fc ON fc.id = swap_requests.from_character_id
LEFT JOIN characters tc ON tc.id = swap_requests.to_character_id
WHERE a.lobby_id = $1 AND swap_requests.status = 'pending'
ORDER BY swap_requests.created_at, swap_requests.id
`

type ListLobbySwapRequestsRow struct {
	SwapRequest  SwapRequest
	UserID       pgtype.UUID
	FromRole     string
	Username     string
	GlobalName   pgtype.Text
	FromNick     pgtype.Text
	FromClassID  pgtype.Text
	FromLevel    pgtype.Int2
	FromPortrait pgtype.Text
	ToNick       pgtype.Text
	ToClassID    pgtype.Text
	ToLevel      pgtype.Int2
	ToPortrait   pgtype.Text
}

// D-12: pedidos pendentes do lobby, com o membro, o personagem atual e o novo (só o dono vê).
func (q *Queries) ListLobbySwapRequests(ctx context.Context, lobbyID pgtype.UUID) ([]ListLobbySwapRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLobbySwapRequests, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLobbySwapRequestsRow
	for rows.Next() {
		var i ListLobbySwapRequestsRow
		if err := rows.Scan(
			&i.SwapRequest.ID,
			&i.SwapRequest.ApplicationID,
			&i.SwapRequest.FromCharacterID,
			&i.SwapRequest.ToCharacterID,
			&i.SwapRequest.ToRole,
			&i.SwapRequest.Reason,
			&i.SwapRequest.Status,
			&i.SwapRequest.DecisionReason,
			&i.SwapRequest.CreatedAt,
			&i.SwapRequest.DecidedAt,
			&i.UserID,
			&i.FromRole,
			&i.Username,
			&i.GlobalName,
			&i.FromNick,
			&i.FromClassID,
			&i.FromLevel,
			&i.FromPortrait,
			&i.ToNick,
			&i.ToClassID,
			&i.ToLevel,
			&i.ToPortrait,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSwapRequestEvents = `-- name: ListSwapRequestEvents :many
SELECT id, swap_request_id, from_status, to_status, actor_id, reason, at FROM swap_request_events WHERE swap_request_id = $1 ORDER BY at, id
`

func (q *Queries) ListSwapRequestEvents(ctx context.Context, swapRequestID pgtype.UUID) ([]SwapRequestEvent, error) {
	rows, err := q.db.Query(ctx, listSwapRequestEvents, swapRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SwapRequestEvent
	for rows.Next() {
		var i SwapRequestEvent
		if err := rows.Scan(
			&i.ID,
			&i.SwapRequestID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.Reason,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSwapRequestStatus = `-- name: SetSwapRequestStatus :one
UPDATE swap_requests
SET status = $1, decision_reason = $2, decided_at = $3::timestamptz
WHERE id = $4
RETURNING id, application_id, from_character_id, to_character_id, to_role, reason, status, decision_reason, created_at, decided_at
`

type SetSwapRequestStatusParams struct {
	Status         string
	DecisionReason pgtype.Text
	Now            time.Time
	ID             pgtype.UUID
}

func (q *Queries) SetSwapRequestStatus(ctx context.Context, arg SetSwapRequestStatusParams) (SwapRequest, error) {
	row := q.db.QueryRow(ctx, setSwapRequestStatus,
		arg.Status,
		arg.DecisionReason,
		arg.Now,
		arg.ID,
	)
	var i SwapRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromCharacterID,
		&i.ToCharacterID,
		&i.ToRole,
		&i.Reason,
		&i.Status,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}
