// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talents.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const affinity = `-- name: Affinity :many
SELECT c.id, c.nick, c.class_id, c.level, c.role, c.portrait, c.link,
       a.days, a.start_minute, a.end_minute, a.any_instance, a.instance_ids, u.username,
       -- RN-13: a pessoa já foi removida deste lobby, e se com bloqueio.
       EXISTS (SELECT 1 FROM applications ap
               WHERE ap.lobby_id = $1::uuid AND ap.user_id = c.user_id
                 AND ap.status = 'removed')::boolean AS removed,
       EXISTS (SELECT 1 FROM applications ap
               WHERE ap.lobby_id = $1::uuid AND ap.user_id = c.user_id
                 AND ap.status = 'removed' AND ap.blocked)::boolean AS blocked
FROM character_availability a
JOIN characters c ON c.id = a.character_id
JOIN users u ON u.id = c.user_id
WHERE a.enabled
  AND c.user_id <> $2
  AND (a.any_instance OR $3::text = ANY (a.instance_ids))
  AND ((a.start_minute < a.end_minute
        AND a.days & (1 << $4::int) <> 0
        AND $5::int >= a.start_minute AND $5::int < a.end_minute)
    OR (a.start_minute > a.end_minute
        AND ((a.days & (1 << $4::int) <> 0 AND $5::int >= a.start_minute)
          OR (a.days & (1 << (($4::int + 6) % 7)) <> 0 AND $5::int < a.end_minute))))
  AND c.level >= $6::int
  AND c.role = ANY ($7::text[])
  AND NOT EXISTS (
      SELECT 1 FROM lobbies l
      WHERE l.cancelled_at IS NULL
        AND l.starts_at > $8 AND l.starts_at < $9
        AND (l.owner_character_id = c.id
             OR EXISTS (SELECT 1 FROM applications ap
                        WHERE ap.lobby_id = l.id AND ap.character_id = c.id
                          AND ap.status IN ('pending', 'accepted'))))
ORDER BY c.level DESC, lower(c.nick), c.seq
`

type AffinityParams struct {
	LobbyID       pgtype.UUID
	ExcludeUserID pgtype.UUID
	InstanceID    string
	Dow           int32
	Minute        int32
	MinLevel      int32
	Roles         []string
	WindowStart   time.Time
	WindowEnd     time.Time
}

type AffinityRow struct {
	ID          pgtype.UUID
	Nick        string
	ClassID     string
	Level       int16
	Role        string
	Portrait    string
	Link        pgtype.Text
	Days        int16
	StartMinute int16
	EndMinute   int16
	AnyInstance bool
	InstanceIds []string
	Username    string
	Removed     bool
	Blocked     bool
}

// RN-06 a RN-08 / D-04: personagens do banco com afinidade com um lobby (gravado ou na
// criação). dow e minute são o início do lobby em Brasília (D-01); a janela é o início
// ± 2 h (D-03 da lobbies).
func (q *Queries) Affinity(ctx context.Context, arg AffinityParams) ([]AffinityRow, error) {
	rows, err := q.db.Query(ctx, affinity,
		arg.LobbyID,
		arg.ExcludeUserID,
		arg.InstanceID,
		arg.Dow,
		arg.Minute,
		arg.MinLevel,
		arg.Roles,
		arg.WindowStart,
		arg.WindowEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AffinityRow
	for rows.Next() {
		var i AffinityRow
		if err := rows.Scan(
			&i.ID,
			&i.Nick,
			&i.ClassID,
			&i.Level,
			&i.Role,
			&i.Portrait,
			&i.Link,
			&i.Days,
			&i.StartMinute,
			&i.EndMinute,
			&i.AnyInstance,
			&i.InstanceIds,
			&i.Username,
			&i.Removed,
			&i.Blocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const catalog = `-- name: Catalog :many
SELECT c.id, c.nick, c.class_id, c.level, c.role, c.portrait, c.link,
       a.days, a.start_minute, a.end_minute, a.any_instance, a.instance_ids, u.username
FROM character_availability a
JOIN characters c ON c.id = a.character_id
JOIN users u ON u.id = c.user_id
WHERE a.enabled
  AND ($1::text IS NULL OR a.any_instance
       OR $1::text = ANY (a.instance_ids))
  AND ($2::text IS NULL OR c.role = $2::text)
  AND ($3::int IS NULL
       OR a.days & (1 << $3::int) <> 0
       OR (a.start_minute > a.end_minute AND $4::int IS NULL
           AND a.days & (1 << (($3::int + 6) % 7)) <> 0)
       OR (a.start_minute > a.end_minute AND $4::int < a.end_minute
           AND a.days & (1 << (($3::int + 6) % 7)) <> 0))
  AND ($4::int IS NULL
       OR (a.start_minute < a.end_minute
           AND $4::int >= a.start_minute AND $4::int < a.end_minute
           AND ($3::int IS NULL OR a.days & (1 << $3::int) <> 0))
       OR (a.start_minute > a.end_minute
           AND (($4::int >= a.start_minute
                 AND ($3::int IS NULL OR a.days & (1 << $3::int) <> 0))
             OR ($4::int < a.end_minute
                 AND ($3::int IS NULL
                      OR a.days & (1 << (($3::int + 6) % 7)) <> 0)))))
ORDER BY c.level DESC, lower(c.nick), c.seq
LIMIT $5
`

type CatalogParams struct {
	InstanceID pgtype.Text
	Role       pgtype.Text
	Dow        pgtype.Int4
	Minute     pgtype.Int4
	MaxRows    int32
}

type CatalogRow struct {
	ID          pgtype.UUID
	Nick        string
	ClassID     string
	Level       int16
	Role        string
	Portrait    string
	Link        pgtype.Text
	Days        int16
	StartMinute int16
	EndMinute   int16
	AnyInstance bool
	InstanceIds []string
	Username    string
}

// RN-11 / RN-08: o banco com filtros opcionais, combinados com "E". Com dia e hora, a
// hora cai na faixa daquele dia (RN-03); só com o dia, a faixa toca o dia; só com a hora,
// a hora cai na faixa em qualquer dia.
func (q *Queries) Catalog(ctx context.Context, arg CatalogParams) ([]CatalogRow, error) {
	rows, err := q.db.Query(ctx, catalog,
		arg.InstanceID,
		arg.Role,
		arg.Dow,
		arg.Minute,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogRow
	for rows.Next() {
		var i CatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Nick,
			&i.ClassID,
			&i.Level,
			&i.Role,
			&i.Portrait,
			&i.Link,
			&i.Days,
			&i.StartMinute,
			&i.EndMinute,
			&i.AnyInstance,
			&i.InstanceIds,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disableAvailability = `-- name: DisableAvailability :one
UPDATE character_availability SET enabled = false, updated_at = $1
WHERE character_id = $2
RETURNING character_id, enabled, days, start_minute, end_minute, any_instance, instance_ids, updated_at
`

type DisableAvailabilityParams struct {
	Now         time.Time
	CharacterID pgtype.UUID
}

// RN-01: desligar tira do banco e guarda os dados.
func (q *Queries) DisableAvailability(ctx context.Context, arg DisableAvailabilityParams) (CharacterAvailability, error) {
	row := q.db.QueryRow(ctx, disableAvailability, arg.Now, arg.CharacterID)
	var i CharacterAvailability
	err := row.Scan(
		&i.CharacterID,
		&i.Enabled,
		&i.Days,
		&i.StartMinute,
		&i.EndMinute,
		&i.AnyInstance,
		&i.InstanceIds,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailabilityByUser = `-- name: ListAvailabilityByUser :many
SELECT a.character_id, a.enabled, a.days, a.start_minute, a.end_minute, a.any_instance, a.instance_ids, a.updated_at FROM character_availability a
JOIN characters c ON c.id = a.character_id
WHERE c.user_id = $1
`

// A disponibilidade de cada personagem do Usuário, para o perfil (CA-01.4).
func (q *Queries) ListAvailabilityByUser(ctx context.Context, userID pgtype.UUID) ([]CharacterAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterAvailability
	for rows.Next() {
		var i CharacterAvailability
		if err := rows.Scan(
			&i.CharacterID,
			&i.Enabled,
			&i.Days,
			&i.StartMinute,
			&i.EndMinute,
			&i.AnyInstance,
			&i.InstanceIds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAvailability = `-- name: UpsertAvailability :one

INSERT INTO character_availability
    (character_id, enabled, days, start_minute, end_minute, any_instance, instance_ids, updated_at)
VALUES ($1, true, $2, $3, $4, $5, $6::text[], $7)
ON CONFLICT (character_id) DO UPDATE
SET enabled = true, days = EXCLUDED.days, start_minute = EXCLUDED.start_minute,
    end_minute = EXCLUDED.end_minute, any_instance = EXCLUDED.any_instance,
    instance_ids = EXCLUDED.instance_ids, updated_at = EXCLUDED.updated_at
RETURNING character_id, enabled, days, start_minute, end_minute, any_instance, instance_ids, updated_at
`

type UpsertAvailabilityParams struct {
	CharacterID pgtype.UUID
	Days        int16
	StartMinute int16
	EndMinute   int16
	AnyInstance bool
	InstanceIds []string
	Now         time.Time
}

// Banco de talentos (spec banco-de-talentos, design D-01 a D-05).
// RN-01 a RN-04: grava a disponibilidade ligada do personagem.
func (q *Queries) UpsertAvailability(ctx context.Context, arg UpsertAvailabilityParams) (CharacterAvailability, error) {
	row := q.db.QueryRow(ctx, upsertAvailability,
		arg.CharacterID,
		arg.Days,
		arg.StartMinute,
		arg.EndMinute,
		arg.AnyInstance,
		arg.InstanceIds,
		arg.Now,
	)
	var i CharacterAvailability
	err := row.Scan(
		&i.CharacterID,
		&i.Enabled,
		&i.Days,
		&i.StartMinute,
		&i.EndMinute,
		&i.AnyInstance,
		&i.InstanceIds,
		&i.UpdatedAt,
	)
	return i, err
}
