// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByDiscordID = `-- name: CountUsersByDiscordID :one
SELECT count(*) FROM users WHERE discord_id = $1
`

func (q *Queries) CountUsersByDiscordID(ctx context.Context, discordID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByDiscordID, discordID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertUserByDiscordID = `-- name: UpsertUserByDiscordID :one
INSERT INTO users (discord_id, username, global_name, created_at, last_login_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (discord_id) DO UPDATE
SET username      = EXCLUDED.username,
    global_name   = EXCLUDED.global_name,
    last_login_at = EXCLUDED.last_login_at
RETURNING id, discord_id, username, global_name, created_at, last_login_at
`

type UpsertUserByDiscordIDParams struct {
	DiscordID  string
	Username   string
	GlobalName pgtype.Text
	Now        time.Time
}

// RN-05: o ID do Discord identifica o Usuário; logins seguintes atualizam os nomes.
func (q *Queries) UpsertUserByDiscordID(ctx context.Context, arg UpsertUserByDiscordIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByDiscordID,
		arg.DiscordID,
		arg.Username,
		arg.GlobalName,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.Username,
		&i.GlobalName,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
